// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type DealersGetResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}

type DealersListItem struct {
	City         string          `json:"city"`
	Country      string          `json:"country"`
	DealerId     string          `json:"dealer_id"`
	Latitude     string          `json:"latitude"`
	ListingCount float64         `json:"listing_count"`
	Longitude    string          `json:"longitude"`
	Makes        json.RawMessage `json:"makes"`
	Name         string          `json:"name"`
	State        string          `json:"state"`
	Type         string          `json:"type"`
	Website      string          `json:"website"`
}

type FacetsListResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}

type HttpApiDecodeError struct {
	Issues  json.RawMessage `json:"issues"`
	Message string          `json:"message"`
}

type Issue struct {
	Message string          `json:"message"`
	Path    json.RawMessage `json:"path"`
}

type ListingsDealersItem struct {
	BaseExteriorColor string          `json:"base_exterior_color"`
	BaseInteriorColor string          `json:"base_interior_color"`
	BodyType          string          `json:"body_type"`
	City              string          `json:"city"`
	Cylinders         string          `json:"cylinders"`
	DaysOnMarket      string          `json:"days_on_market"`
	DealerId          string          `json:"dealer_id"`
	DealerName        string          `json:"dealer_name"`
	DistanceMiles     string          `json:"distance_miles"`
	Doors             string          `json:"doors"`
	Drivetrain        string          `json:"drivetrain"`
	Engine            string          `json:"engine"`
	ExteriorColor     string          `json:"exterior_color"`
	FuelType          string          `json:"fuel_type"`
	Id                string          `json:"id"`
	InteriorColor     string          `json:"interior_color"`
	InventoryStatus   string          `json:"inventory_status"`
	InventoryType     string          `json:"inventory_type"`
	Latitude          string          `json:"latitude"`
	Longitude         string          `json:"longitude"`
	Make              string          `json:"make"`
	Miles             string          `json:"miles"`
	Model             string          `json:"model"`
	Msrp              string          `json:"msrp"`
	PhotoUrls         json.RawMessage `json:"photo_urls"`
	PowertrainType    string          `json:"powertrain_type"`
	Price             string          `json:"price"`
	PriceHistory      json.RawMessage `json:"price_history"`
	SeatingCapacity   string          `json:"seating_capacity"`
	SoldDate          string          `json:"sold_date"`
	State             string          `json:"state"`
	Status            string          `json:"status"`
	StockNumber       string          `json:"stock_number"`
	Transmission      string          `json:"transmission"`
	Trim              string          `json:"trim"`
	VdpUrl            string          `json:"vdp_url"`
	Version           string          `json:"version"`
	Vin               string          `json:"vin"`
	Year              string          `json:"year"`
}

type ListingsGetResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}

type ListingsListItem struct {
	BaseExteriorColor string          `json:"base_exterior_color"`
	BaseInteriorColor string          `json:"base_interior_color"`
	BodyType          string          `json:"body_type"`
	City              string          `json:"city"`
	Cylinders         string          `json:"cylinders"`
	DaysOnMarket      string          `json:"days_on_market"`
	DealerId          string          `json:"dealer_id"`
	DealerName        string          `json:"dealer_name"`
	DistanceMiles     string          `json:"distance_miles"`
	Doors             string          `json:"doors"`
	Drivetrain        string          `json:"drivetrain"`
	Engine            string          `json:"engine"`
	ExteriorColor     string          `json:"exterior_color"`
	FuelType          string          `json:"fuel_type"`
	Id                string          `json:"id"`
	InteriorColor     string          `json:"interior_color"`
	InventoryStatus   string          `json:"inventory_status"`
	InventoryType     string          `json:"inventory_type"`
	Latitude          string          `json:"latitude"`
	Longitude         string          `json:"longitude"`
	Make              string          `json:"make"`
	Miles             string          `json:"miles"`
	Model             string          `json:"model"`
	Msrp              string          `json:"msrp"`
	PhotoUrls         json.RawMessage `json:"photo_urls"`
	PowertrainType    string          `json:"powertrain_type"`
	Price             string          `json:"price"`
	PriceHistory      json.RawMessage `json:"price_history"`
	SeatingCapacity   string          `json:"seating_capacity"`
	SoldDate          string          `json:"sold_date"`
	State             string          `json:"state"`
	Status            string          `json:"status"`
	StockNumber       string          `json:"stock_number"`
	Transmission      string          `json:"transmission"`
	Trim              string          `json:"trim"`
	VdpUrl            string          `json:"vdp_url"`
	Version           string          `json:"version"`
	Vin               string          `json:"vin"`
	Year              string          `json:"year"`
}

type PublicApiAuthenticationError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiBillingError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiNotFoundError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiPermissionError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiPlatformError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiValidationError struct {
	Error json.RawMessage `json:"error"`
}

type UsagePublicItem struct {
	ChargedMicros float64 `json:"charged_micros"`
	Date          string  `json:"date"`
	MeteringClass string  `json:"metering_class"`
	Requests      float64 `json:"requests"`
}

type VinsGetResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}
