// Copyright 2026 Visor. Licensed under Apache-2.0. See LICENSE.
// Portions generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press).

package types

import "encoding/json"

type DealersGetResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}

type DealersListItem struct {
	City         string          `json:"city"`
	Country      string          `json:"country"`
	DealerId     string          `json:"dealer_id"`
	Latitude     string          `json:"latitude"`
	ListingCount float64         `json:"listing_count"`
	Longitude    string          `json:"longitude"`
	Makes        json.RawMessage `json:"makes"`
	Name         string          `json:"name"`
	State        string          `json:"state"`
	Type         string          `json:"type"`
	Website      string          `json:"website"`
}

type FacetsListResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}

type HttpApiDecodeError struct {
	Issues  json.RawMessage `json:"issues"`
	Message string          `json:"message"`
}

type Issue struct {
	Message string          `json:"message"`
	Path    json.RawMessage `json:"path"`
}

type ListingsDealersItem struct {
	City            string          `json:"city"`
	DaysOnMarket    string          `json:"days_on_market"`
	DealerId        string          `json:"dealer_id"`
	DealerName      string          `json:"dealer_name"`
	DistanceMiles   string          `json:"distance_miles"`
	Id              string          `json:"id"`
	InventoryStatus string          `json:"inventory_status"`
	InventoryType   string          `json:"inventory_type"`
	Latitude        string          `json:"latitude"`
	Longitude       string          `json:"longitude"`
	Make            string          `json:"make"`
	Miles           string          `json:"miles"`
	Model           string          `json:"model"`
	PhotoUrls       json.RawMessage `json:"photo_urls"`
	Price           string          `json:"price"`
	State           string          `json:"state"`
	Status          string          `json:"status"`
	StockNumber     string          `json:"stock_number"`
	Trim            string          `json:"trim"`
	VdpUrl          string          `json:"vdp_url"`
	Vin             string          `json:"vin"`
	Year            string          `json:"year"`
}

type ListingsGetResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}

type ListingsListItem struct {
	City            string          `json:"city"`
	DaysOnMarket    string          `json:"days_on_market"`
	DealerId        string          `json:"dealer_id"`
	DealerName      string          `json:"dealer_name"`
	DistanceMiles   string          `json:"distance_miles"`
	Id              string          `json:"id"`
	InventoryStatus string          `json:"inventory_status"`
	InventoryType   string          `json:"inventory_type"`
	Latitude        string          `json:"latitude"`
	Longitude       string          `json:"longitude"`
	Make            string          `json:"make"`
	Miles           string          `json:"miles"`
	Model           string          `json:"model"`
	PhotoUrls       json.RawMessage `json:"photo_urls"`
	Price           string          `json:"price"`
	State           string          `json:"state"`
	Status          string          `json:"status"`
	StockNumber     string          `json:"stock_number"`
	Trim            string          `json:"trim"`
	VdpUrl          string          `json:"vdp_url"`
	Vin             string          `json:"vin"`
	Year            string          `json:"year"`
}

type PublicApiAuthenticationError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiBillingError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiNotFoundError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiPermissionError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiPlatformError struct {
	Error json.RawMessage `json:"error"`
}

type PublicApiValidationError struct {
	Error json.RawMessage `json:"error"`
}

type VinsGetResponse struct {
	Data json.RawMessage `json:"data"`
	Meta json.RawMessage `json:"meta"`
}
