// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDealersListCmd(flags *rootFlags) *cobra.Command {
	var flagLimit string
	var flagOffset string
	var flagDealerId string
	var flagState string
	var flagCountry string
	var flagType string
	var flagMake string
	var flagQ string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Returns public dealer summaries ordered by active listing count. Listing counts use VIN-level listing deduplication...",
		Example:     "  visor dealers list",
		Annotations: map[string]string{"pp:endpoint": "dealers.list", "pp:method": "GET", "pp:path": "/v1/dealers", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("type") {
				allowedType := []string{"franchise", "independent"}
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "type", flagType, allowedType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/dealers"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "dealers", path, map[string]string{
				"limit":     fmt.Sprintf("%v", flagLimit),
				"offset":    fmt.Sprintf("%v", flagOffset),
				"dealer_id": fmt.Sprintf("%v", flagDealerId),
				"state":     fmt.Sprintf("%v", flagState),
				"country":   fmt.Sprintf("%v", flagCountry),
				"type":      fmt.Sprintf("%v", flagType),
				"make":      fmt.Sprintf("%v", flagMake),
				"q":         fmt.Sprintf("%v", flagQ),
			}, nil, flagAll, "offset", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance first so --select paths match
			// the documented envelope shape, e.g. results.data.vin.
			if flags.asJSON || flags.markdown || !isTerminal(cmd.OutOrStdout()) {
				wrapped, wrapErr := wrapWithProvenance(data, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutputWithFlags(cmd.OutOrStdout(), wrapped, flags)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Page size as an integer string. Defaults to 50; maximum 100.")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "Zero-based page offset as an integer string. Defaults to 0.")
	cmd.Flags().StringVar(&flagDealerId, "dealer-id", "", "Comma-separated dealer UUIDs to fetch directly. Accepts up to 100 dealer IDs.")
	cmd.Flags().StringVar(&flagState, "state", "", "Comma-separated two-letter dealer states, for example CA,TX.")
	cmd.Flags().StringVar(&flagCountry, "country", "", "Dealer country code, for example US.")
	cmd.Flags().StringVar(&flagType, "type", "", "Dealer type. (one of: franchise, independent)")
	cmd.Flags().StringVar(&flagMake, "make", "", "Comma-separated represented franchise makes or slugs, for example toyota,honda.")
	cmd.Flags().StringVar(&flagQ, "q", "", "Case-insensitive dealer name or website domain search string.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
