// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDealersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "dealers",
		Short: "Manage dealers",
	}

	cmd.AddCommand(newDealersGetCmd(flags))
	cmd.AddCommand(newDealersListCmd(flags))
	cmd.AddCommand(newDealersListingsCmd(flags))
	return cmd
}
