// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"github.com/visorvin/cli/internal/client"
	"github.com/visorvin/cli/internal/cliutil"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/tabwriter"
	"time"
	"unicode"
)

var As = errors.As

// noColor is set by the --no-color flag
var noColor bool

// humanFriendly is set by the --human-friendly flag; colors are off by default (agent-safe)
var humanFriendly bool

func colorEnabled() bool {
	if noColor {
		return false
	}
	if !humanFriendly {
		return false
	}
	if os.Getenv("NO_COLOR") != "" {
		return false
	}
	if os.Getenv("TERM") == "dumb" {
		return false
	}
	return isTerminal(os.Stdout)
}

func isTerminal(w io.Writer) bool {
	if f, ok := w.(*os.File); ok {
		fi, err := f.Stat()
		if err != nil {
			return true
		}
		return (fi.Mode() & os.ModeCharDevice) != 0
	}
	return false
}

func bold(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[1m" + s + "\033[0m"
}

func green(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[32m" + s + "\033[0m"
}

func red(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[31m" + s + "\033[0m"
}

func yellow(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[33m" + s + "\033[0m"
}

type cliError struct {
	code int
	err  error
}

func (e *cliError) Error() string { return e.err.Error() }
func (e *cliError) Unwrap() error { return e.err }

func usageErr(err error) error     { return &cliError{code: 2, err: err} }
func notFoundErr(err error) error  { return &cliError{code: 3, err: err} }
func authErr(err error) error      { return &cliError{code: 4, err: err} }
func apiErr(err error) error       { return &cliError{code: 5, err: err} }
func configErr(err error) error    { return &cliError{code: 10, err: err} }
func rateLimitErr(err error) error { return &cliError{code: 7, err: err} }

// dryRunOK reports whether the command should short-circuit without doing any
// real work because --dry-run was set. The verify pipeline probes hand-written
// commands with --dry-run; commands that put validation in cobra's `Args:` or
// `MarkFlagRequired` cannot reach a dry-run guard inside RunE because cobra
// runs those checks before RunE. The verify-friendly pattern for hand-written
// commands is:
//
//	RunE: func(cmd *cobra.Command, args []string) error {
//	    if len(args) == 0 {
//	        return cmd.Help()
//	    }
//	    if dryRunOK(flags) {
//	        return nil
//	    }
//	    // ... real work ...
//	}
//
// See SKILL.md "Phase 3: Build The GOAT" for the full pattern.
func dryRunOK(flags *rootFlags) bool {
	return flags != nil && flags.dryRun
}

// accessWarning describes an API access-denial that sync converts into a
// non-fatal warning. It carries enough structured data for the sync_warning
// JSON event without parsing free-form error strings downstream.
type accessWarning struct {
	Status  int    // HTTP status when applicable; 0 for GraphQL field-level denials.
	Reason  string // "forbidden" | "insufficient_access" | "unauthenticated"
	Message string // human-readable detail (the API's body or GraphQL error message)
}

// accessDenialPatterns matches API error bodies that indicate the request was
// rejected for access-policy reasons rather than for input validity. Matching
// is case-insensitive and uses word boundaries so common substrings inside
// unrelated tokens (e.g. "author", "pagination_token", "insufficient_funds")
// do not produce false positives. The set deliberately excludes brand names —
// vendor-specific phrasings should be addressed at the spec/profiler level,
// not in this universal classifier.
var accessDenialPatterns = []*regexp.Regexp{
	regexp.MustCompile(`\bforbidden\b`),
	regexp.MustCompile(`\bunauthorized\b`),
	regexp.MustCompile(`\bnot[\s_-]?authorized\b`),
	regexp.MustCompile(`\bpermission[\s_-]?denied\b`),
	regexp.MustCompile(`\baccess[\s_-]?denied\b`),
	regexp.MustCompile(`\binsufficient[\s_-]?(scope|permission|privilege)`),
	regexp.MustCompile(`\binvalid[\s_-]?scope\b`),
	regexp.MustCompile(`\bmissing[\s_-]?scope\b`),
	regexp.MustCompile(`\brequires?\s+(elevated|admin|enterprise|business|workspace|enterprise[\s_-]?tier)`),
}

// looksLikeAccessDenial reports whether body text describes an access-policy
// rejection. Use it on response-body content (apiErr.Body), not on the full
// error string — the request path can contain words like "auth" or "tokens"
// that would produce false positives if the whole error message were scanned.
func looksLikeAccessDenial(body string) bool {
	lower := strings.ToLower(body)
	for _, p := range accessDenialPatterns {
		if p.MatchString(lower) {
			return true
		}
	}
	return false
}

// isSyncAccessWarning classifies err as an access-denial warning suitable for
// sync's warn-and-continue path. It returns nil, false for any error that
// should remain a hard sync failure: HTTP 401 (token-level auth failure
// requiring re-auth), 5xx, network errors, and HTTP 400 responses whose
// bodies do not match an access-policy pattern.
//
// Recognized warning shapes:
//   - HTTP 403 (per-resource ACL rejection)
//   - HTTP 400 + access-denial body keyword (insufficient scope, etc.)
//   - GraphQL response carrying only access-denial extension codes
func isSyncAccessWarning(err error) (*accessWarning, bool) {
	if err == nil {
		return nil, false
	}

	var apiErr *client.APIError
	if errors.As(err, &apiErr) {
		switch apiErr.StatusCode {
		case 403:
			return &accessWarning{Status: 403, Reason: "forbidden", Message: apiErr.Body}, true
		case 400:
			if looksLikeAccessDenial(apiErr.Body) {
				return &accessWarning{Status: 400, Reason: "insufficient_access", Message: apiErr.Body}, true
			}
		}
	}

	return nil, false
}

type noopResult struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
}

func writeNoop(flags *rootFlags, reason, prose string) error {
	if flags != nil && flags.asJSON {
		return json.NewEncoder(os.Stdout).Encode(noopResult{Status: "noop", Reason: reason})
	}
	fmt.Fprintln(os.Stderr, prose)
	return nil
}

func writeAPIErrorEnvelope(flags *rootFlags, err error, code int) {
	if flags == nil || !flags.asJSON {
		return
	}
	_ = json.NewEncoder(os.Stdout).Encode(map[string]any{
		"error": err.Error(),
		"code":  code,
	})
}

// classifyAPIError maps API errors to structured exit codes with actionable hints.
func classifyAPIError(err error, flags *rootFlags) error {
	msg := err.Error()
	switch {
	case strings.Contains(msg, "HTTP 409"):
		if flags != nil && flags.idempotent {
			return writeNoop(flags, "already_exists", "already exists (no-op)")
		}
		classified := apiErr(err)
		writeAPIErrorEnvelope(flags, classified, ExitCode(classified))
		return classified
	case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
		return authErr(fmt.Errorf("%w\nhint: the API rejected the request — this usually means auth is missing or invalid."+
			"\n      Set your API key: export VISOR_API_KEY=<your-key>"+
			"\n      Run 'visor doctor' to check auth status."+
			"\n      Response: "+cliutil.SanitizeErrorBody(msg), err))
	case strings.Contains(msg, "HTTP 401"):
		return authErr(fmt.Errorf("%w\nhint: check your token. Pipe it with: printf '%%s' \"$VISOR_API_KEY\" | visor auth set-token --stdin"+
			"\n      or: export VISOR_API_KEY=<your-token>"+
			"\n      Run 'visor doctor' to check auth status.", err))
	case strings.Contains(msg, "HTTP 403"):
		return authErr(fmt.Errorf("%w\nhint: permission denied. Your credentials are valid but lack access to this resource."+
			"\n      Check that your API key has the required permissions."+
			"\n      Set it with: export VISOR_API_KEY=<your-key>"+
			"\n      Run 'visor doctor' to check auth status.", err))
	case strings.Contains(msg, "HTTP 404"):
		return notFoundErr(fmt.Errorf("%w\nhint: resource not found. Run the 'list' command to see available items", err))
	case strings.Contains(msg, "HTTP 429"):
		return rateLimitErr(err)
	default:
		return apiErr(err)
	}
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	if max <= 3 {
		return s[:max]
	}
	return s[:max-3] + "..."
}

func newTabWriter(w io.Writer) *tabwriter.Writer {
	return tabwriter.NewWriter(w, 2, 4, 2, ' ', 0)
}
func replacePathParam(path, name, value string) string {
	return strings.ReplaceAll(path, "{"+name+"}", value)
}

// paginatedGet fetches pages and concatenates array results. The headers
// argument carries per-endpoint required headers (e.g. cal-api-version) that
// must be sent on every page request, including the first; pass nil when the
// endpoint has no per-endpoint header overrides.
func paginatedGet(c interface {
	GetWithHeaders(path string, params map[string]string, headers map[string]string) (json.RawMessage, error)
}, path string, params map[string]string, headers map[string]string, fetchAll bool, cursorParam, nextCursorPath, hasMoreField string) (json.RawMessage, error) {
	// Clean zero-value params
	clean := map[string]string{}
	for k, v := range params {
		if v != "" && v != "0" && v != "false" {
			clean[k] = v
		}
	}

	if !fetchAll {
		return c.GetWithHeaders(path, clean, headers)
	}

	// Fetch all pages
	var allItems []json.RawMessage
	page := 0
	for {
		page++
		if humanFriendly {
			fmt.Fprintf(os.Stderr, "fetching page %d...\n", page)
		} else {
			fmt.Fprintf(os.Stderr, `{"event":"page_fetch","page":%d}`+"\n", page)
		}

		data, err := c.GetWithHeaders(path, clean, headers)
		if err != nil {
			return nil, err
		}

		// Try to extract items array
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			allItems = append(allItems, items...)
		} else {
			// Response is an object - look for array inside
			var obj map[string]json.RawMessage
			if json.Unmarshal(data, &obj) == nil {
				itemsBefore := len(allItems)
				// Try common data fields
				for _, field := range []string{"data", "items", "results", "messages", "members", "values"} {
					if arr, ok := obj[field]; ok {
						var nested []json.RawMessage
						if json.Unmarshal(arr, &nested) == nil {
							allItems = append(allItems, nested...)
							break
						}
					}
				}
				itemsAdded := len(allItems) - itemsBefore

				// Check for next cursor
				if nextCursorPath != "" {
					if tokenRaw, ok := obj[nextCursorPath]; ok {
						var token string
						if json.Unmarshal(tokenRaw, &token) == nil && token != "" {
							clean[cursorParam] = token
							continue
						}
					}
				}

				// Check has_more
				if hasMoreField != "" {
					if moreRaw, ok := obj[hasMoreField]; ok {
						var more bool
						if json.Unmarshal(moreRaw, &more) == nil && more {
							continue
						}
					}
				}

				if nextOffset, ok := nextOffsetFromEnvelope(obj, clean, itemsAdded); ok {
					clean["offset"] = fmt.Sprintf("%d", nextOffset)
					continue
				}
			}
			// No more pages
			break
		}

		// For direct arrays, can't paginate without cursor
		break
	}

	if humanFriendly {
		fmt.Fprintf(os.Stderr, "fetched %d items across %d pages\n", len(allItems), page)
	} else {
		fmt.Fprintf(os.Stderr, `{"event":"complete","total":%d,"pages":%d}`+"\n", len(allItems), page)
	}
	result, _ := json.Marshal(allItems)
	return json.RawMessage(result), nil
}

func nextOffsetFromEnvelope(obj map[string]json.RawMessage, params map[string]string, itemsAdded int) (int, bool) {
	if itemsAdded <= 0 {
		return 0, false
	}
	paginationRaw, ok := obj["pagination"]
	if !ok {
		if metaRaw, hasMeta := obj["meta"]; hasMeta {
			paginationRaw = metaRaw
		}
	}
	if len(paginationRaw) == 0 {
		return 0, false
	}
	var pagination map[string]json.RawMessage
	if json.Unmarshal(paginationRaw, &pagination) != nil {
		return 0, false
	}
	total, hasTotal := intFromJSONFields(pagination, "total", "total_available", "total_count", "count")
	limit, hasLimit := intFromJSONFields(pagination, "limit", "page_size", "per_page")
	offset, hasOffset := intFromJSONFields(pagination, "offset", "skip")
	if !hasOffset {
		offset, _ = atoiDefault(params["offset"], 0)
	}
	if !hasLimit {
		limit, _ = atoiDefault(params["limit"], itemsAdded)
	}
	if limit <= 0 {
		limit = itemsAdded
	}
	next := offset + limit
	if itemsAdded < limit {
		return 0, false
	}
	if hasTotal && next >= total {
		return 0, false
	}
	return next, true
}

func intFromJSONFields(obj map[string]json.RawMessage, names ...string) (int, bool) {
	for _, name := range names {
		raw, ok := obj[name]
		if !ok {
			continue
		}
		var n int
		if json.Unmarshal(raw, &n) == nil {
			return n, true
		}
		var f float64
		if json.Unmarshal(raw, &f) == nil {
			return int(f), true
		}
		var s string
		if json.Unmarshal(raw, &s) == nil {
			if parsed, err := atoiDefault(s, 0); err == nil {
				return parsed, true
			}
		}
	}
	return 0, false
}

func atoiDefault(s string, fallback int) (int, error) {
	if strings.TrimSpace(s) == "" {
		return fallback, nil
	}
	n, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil {
		return fallback, err
	}
	return n, nil
}

// printJSONFiltered marshals a Go-typed value through the same output
// pipeline endpoint-mirror commands use. Hand-written novel commands that
// build a typed slice/struct call this so --select, --compact, --csv, and
// --quiet all behave the same way as on generator-emitted commands.
func printJSONFiltered(w io.Writer, v any, flags *rootFlags) error {
	raw, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return printOutputWithFlags(w, json.RawMessage(raw), flags)
}

// filterFields keeps only the specified fields (comma-separated) from JSON objects/arrays.
// Supports dotted paths like "events.shortName" to descend into nested structures.
// Arrays are traversed element-wise: "events.shortName" keeps shortName on each event.
func filterFields(data json.RawMessage, fields string) json.RawMessage {
	filtered, err := filterFieldsValidated(data, fields)
	if err != nil {
		return filterFieldsRec(data, parseSelectPaths(fields))
	}
	return filtered
}

func filterFieldsValidated(data json.RawMessage, fields string) (json.RawMessage, error) {
	paths := expandRowRelativeSelectPaths(data, parseSelectPaths(fields))
	if len(paths) == 0 {
		return data, nil
	}
	invalid := make([]string, 0)
	for _, p := range paths {
		if !selectPathExists(data, p) {
			invalid = append(invalid, strings.Join(p, "."))
		}
	}
	if len(invalid) > 0 {
		valid := validSelectPaths(data, 80)
		msg := fmt.Sprintf("unknown selected field(s): %s", strings.Join(invalid, ", "))
		if len(valid) > 0 {
			msg += "; valid fields include: " + strings.Join(valid, ", ")
		}
		return nil, usageErr(fmt.Errorf(msg))
	}
	return filterFieldsRec(data, paths), nil
}

func expandRowRelativeSelectPaths(data json.RawMessage, paths [][]string) [][]string {
	if len(paths) == 0 || (!selectPathExists(data, []string{"results", "data"}) && !selectPathExists(data, []string{"data"})) {
		return paths
	}
	expanded := make([][]string, 0, len(paths))
	for _, p := range paths {
		if len(p) == 0 || selectPathExists(data, p) {
			expanded = append(expanded, p)
			continue
		}
		candidate := append([]string{"results", "data"}, p...)
		if selectPathExists(data, candidate) {
			expanded = append(expanded, candidate)
			continue
		}
		candidate = append([]string{"data"}, p...)
		if selectPathExists(data, candidate) {
			expanded = append(expanded, candidate)
			continue
		}
		expanded = append(expanded, p)
	}
	return expanded
}

func parseSelectPaths(fields string) [][]string {
	var paths [][]string
	for _, f := range strings.Split(fields, ",") {
		f = strings.TrimSpace(f)
		if f == "" {
			continue
		}
		parts := strings.Split(f, ".")
		for i := range parts {
			parts[i] = strings.ToLower(strings.TrimSpace(parts[i]))
		}
		paths = append(paths, parts)
	}
	return paths
}

func selectPathExists(data json.RawMessage, path []string) bool {
	if len(path) == 0 {
		return true
	}
	var arr []json.RawMessage
	if err := json.Unmarshal(data, &arr); err == nil {
		if len(arr) == 0 {
			return true
		}
		for _, el := range arr {
			if selectPathExists(el, path) {
				return true
			}
		}
		return false
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return false
	}
	for k, v := range obj {
		if selectSegmentMatches(k, path[0]) {
			return selectPathExists(v, path[1:])
		}
	}
	return false
}

func validSelectPaths(data json.RawMessage, limit int) []string {
	seen := map[string]bool{}
	var out []string
	var walk func(json.RawMessage, []string)
	walk = func(raw json.RawMessage, prefix []string) {
		if len(out) >= limit {
			return
		}
		var arr []json.RawMessage
		if err := json.Unmarshal(raw, &arr); err == nil {
			if len(arr) > 0 {
				walk(arr[0], prefix)
			}
			return
		}
		var obj map[string]json.RawMessage
		if err := json.Unmarshal(raw, &obj); err == nil {
			keys := make([]string, 0, len(obj))
			for k := range obj {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				if len(out) >= limit {
					return
				}
				p := append(append([]string{}, prefix...), k)
				var childObj map[string]json.RawMessage
				var childArr []json.RawMessage
				if err := json.Unmarshal(obj[k], &childObj); err == nil {
					walk(obj[k], p)
					continue
				}
				if err := json.Unmarshal(obj[k], &childArr); err == nil && len(childArr) > 0 {
					walk(childArr[0], p)
					continue
				}
				path := strings.Join(p, ".")
				if !seen[path] {
					seen[path] = true
					out = append(out, path)
				}
			}
		}
	}
	walk(data, nil)
	return out
}

// filterFieldsRec applies path filters to a JSON value. Each path is a list of
// lowercase segments; arrays descend element-wise.
func filterFieldsRec(data json.RawMessage, paths [][]string) json.RawMessage {
	var arr []json.RawMessage
	if err := json.Unmarshal(data, &arr); err == nil {
		out := make([]json.RawMessage, len(arr))
		for i, el := range arr {
			out[i] = filterFieldsRec(el, paths)
		}
		result, _ := json.Marshal(out)
		return result
	}

	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err == nil {
		keepWhole := map[string]bool{}
		subPaths := map[string][][]string{}
		for _, p := range paths {
			if len(p) == 0 {
				continue
			}
			head := p[0]
			if len(p) == 1 {
				keepWhole[head] = true
			} else {
				subPaths[head] = append(subPaths[head], p[1:])
			}
		}
		filtered := map[string]json.RawMessage{}
		for k, v := range obj {
			matched := matchSelectSegment(k, keepWhole, subPaths)
			if matched == "" {
				continue
			}
			if keepWhole[matched] {
				filtered[k] = v
				continue
			}
			if subs := subPaths[matched]; subs != nil {
				filtered[k] = filterFieldsRec(v, subs)
			}
		}
		result, _ := json.Marshal(filtered)
		return result
	}

	return data
}

// matchSelectSegment returns the matching lowercase segment, or "" if no match.
// Supports direct case-insensitive match and camelCase→kebab-case conversion.
func matchSelectSegment(fieldName string, keepWhole map[string]bool, subPaths map[string][][]string) string {
	for candidate := range keepWhole {
		if selectSegmentMatches(fieldName, candidate) {
			return candidate
		}
	}
	for candidate := range subPaths {
		if selectSegmentMatches(fieldName, candidate) {
			return candidate
		}
	}
	return ""
}

func selectSegmentMatches(fieldName, requested string) bool {
	lower := strings.ToLower(fieldName)
	if requested == lower {
		return true
	}
	kebab := camelToKebab(fieldName)
	if requested == kebab {
		return true
	}
	snake := strings.ReplaceAll(kebab, "-", "_")
	return requested == snake
}

// camelToKebab converts "orderDate" or "orderdate" to "order-date" by splitting on
// uppercase boundaries. For already-lowercase input, splits on known word boundaries.
func camelToKebab(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && unicode.IsUpper(r) && unicode.IsLower(runes[i-1]) {
			b.WriteByte('-')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// printOutputWithFlags routes output through the right format based on flags.
func printOutputWithFlags(w io.Writer, data json.RawMessage, flags *rootFlags) error {
	if flags != nil && flags.agent {
		data = agentEnvelope(data)
	}
	// --select wins over --compact when both are set: an explicit field list
	// is the user's authoritative request, so compacting must not strip those
	// fields before --select can pick them.
	if flags != nil && flags.selectFields != "" {
		filtered, err := filterFieldsForOutput(data, flags.selectFields, flags)
		if err != nil {
			return err
		}
		data = filtered
	} else if flags != nil && flags.compact {
		data = compactFields(data)
	}
	// --quiet: suppress all output, exit code communicates result
	if flags != nil && flags.quiet {
		return nil
	}
	// --csv: render as CSV
	if flags != nil && flags.csv {
		return printCSV(w, data)
	}
	// --markdown: render as Markdown for transcript-friendly output
	if flags != nil && flags.markdown {
		return printMarkdown(w, data)
	}
	return printOutput(w, data, flags != nil && flags.asJSON)
}

func filterFieldsForOutput(data json.RawMessage, fields string, flags *rootFlags) (json.RawMessage, error) {
	if flags != nil && flags.agent {
		return filterAgentDataFields(data, fields)
	}
	return filterFieldsValidated(data, fields)
}

func filterAgentDataFields(data json.RawMessage, fields string) (json.RawMessage, error) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return filterFieldsValidated(data, fields)
	}
	dataRaw, ok := obj["data"]
	if !ok {
		return filterFieldsValidated(data, fields)
	}
	filtered, err := filterFieldsValidated(dataRaw, agentDataSelectFields(fields))
	if err != nil {
		return nil, err
	}
	obj["data"] = filtered
	return json.Marshal(obj)
}

func agentDataSelectFields(fields string) string {
	paths := parseSelectPaths(fields)
	out := make([]string, 0, len(paths))
	for _, p := range paths {
		if len(p) >= 2 && p[0] == "data" {
			p = p[1:]
		}
		if len(p) >= 3 && p[0] == "results" && p[1] == "data" {
			p = p[2:]
		}
		if len(p) == 0 {
			continue
		}
		out = append(out, strings.Join(p, "."))
	}
	return strings.Join(out, ",")
}

func agentEnvelope(data json.RawMessage) json.RawMessage {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		out, _ := json.Marshal(map[string]any{
			"data":            rawJSONToAny(data),
			"pagination":      map[string]any{},
			"query":           map[string]any{},
			"warnings":        []any{},
			"facets_used":     []any{},
			"total_available": nil,
		})
		return out
	}

	payload := data
	if results, ok := obj["results"]; ok {
		payload = results
	}
	payloadObj := map[string]json.RawMessage{}
	_ = json.Unmarshal(payload, &payloadObj)

	rows := payload
	if nestedData, ok := payloadObj["data"]; ok {
		rows = nestedData
	}
	pagination := json.RawMessage(`{}`)
	if raw, ok := payloadObj["pagination"]; ok {
		pagination = raw
	} else if raw, ok := payloadObj["meta"]; ok {
		pagination = raw
	}
	totalAvailable := any(nil)
	if pmap := map[string]json.RawMessage{}; json.Unmarshal(pagination, &pmap) == nil {
		if n, ok := intFromJSONFields(pmap, "total_available", "total", "total_count", "count"); ok {
			totalAvailable = n
		}
	}
	if totalAvailable == nil {
		var arr []json.RawMessage
		if json.Unmarshal(rows, &arr) == nil {
			totalAvailable = len(arr)
		}
	}

	envelope := map[string]any{
		"data":            rawJSONToAny(rows),
		"pagination":      rawJSONToAny(pagination),
		"query":           map[string]any{},
		"warnings":        []any{},
		"facets_used":     []any{},
		"total_available": totalAvailable,
	}
	if meta, ok := obj["meta"]; ok {
		metaAny := rawJSONToAny(meta)
		envelope["meta"] = metaAny
		if metaObj, ok := metaAny.(map[string]any); ok {
			if query, ok := metaObj["query"]; ok {
				envelope["query"] = query
				envelope["facets_used"] = facetsUsedFromQuery(query)
			}
		}
	}
	result, _ := json.Marshal(envelope)
	return result
}

func facetsUsedFromQuery(query any) []string {
	queryObj, ok := query.(map[string]any)
	if !ok {
		return []string{}
	}
	raw, ok := queryObj["facets"]
	if !ok {
		return []string{}
	}
	facets, ok := raw.(string)
	if !ok {
		return []string{}
	}
	out := make([]string, 0)
	for _, facet := range strings.Split(facets, ",") {
		facet = strings.TrimSpace(facet)
		if facet != "" {
			out = append(out, facet)
		}
	}
	return out
}

// extractResponseData unwraps common API response envelopes for display.
// Many APIs return {"status":"success","data":[...]} instead of a bare array.
// This extracts the inner data for output helpers (filterFields, compactFields,
// printAutoTable) that expect arrays or flat objects.
//
// Only unwraps when a "status" field is present and indicates success — this
// avoids false positives on APIs where "data" is a regular field (e.g., Stripe
// returns {"data":[...],"has_more":true} where "data" is the list, not an
// envelope wrapper).
func extractResponseData(data json.RawMessage) json.RawMessage {
	var envelope struct {
		Status string          `json:"status"`
		Data   json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return data
	}
	if envelope.Data == nil || envelope.Status == "" {
		return data // No status field = not an envelope, might be regular "data" field
	}
	switch envelope.Status {
	case "success", "ok", "OK", "Success":
		return envelope.Data
	default:
		return data
	}
}

// compactFields keeps only the most important fields for agent consumption.
// For arrays: allowlist of high-gravity fields (no descriptions/photos).
// For single objects: blocklist that strips known-verbose fields.
func compactFields(data json.RawMessage) json.RawMessage {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err == nil {
		if results, ok := obj["results"]; ok {
			if raw, err := json.Marshal(results); err == nil {
				obj["results"] = rawJSONToAny(compactFields(json.RawMessage(raw)))
			}
			result, _ := json.Marshal(obj)
			return result
		}
		if dataVal, ok := obj["data"]; ok {
			if raw, err := json.Marshal(dataVal); err == nil {
				obj["data"] = rawJSONToAny(compactFields(json.RawMessage(raw)))
			}
			result, _ := json.Marshal(compactObjectMap(obj))
			return result
		}
		return compactObjectFields(obj)
	}

	var items []map[string]any
	if err := json.Unmarshal(data, &items); err == nil {
		return compactListFields(items)
	}

	return data
}

func rawJSONToAny(raw json.RawMessage) any {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return string(raw)
	}
	return v
}

// compactListFields keeps high-gravity fields for array responses, including
// Visor listing fields agents need to rank and cite vehicles.
func compactListFields(items []map[string]any) json.RawMessage {
	keepFields := map[string]bool{
		"id": true, "name": true, "title": true, "identifier": true,
		"status": true, "state": true, "type": true, "priority": true,
		"url": true, "email": true, "key": true,
		"created_at": true, "updated_at": true, "createdAt": true, "updatedAt": true,
		"listing_id": true, "vin": true, "year": true, "make": true, "model": true,
		"trim": true, "version": true, "price": true, "msrp": true, "miles": true,
		"dealer_id": true, "dealer_name": true, "city": true, "postal_code": true,
		"inventory_type": true, "inventory_status": true, "vdp_url": true,
		"days_on_market": true, "distance": true, "exterior_color": true,
		"interior_color": true,
	}

	filtered := make([]map[string]any, 0, len(items))
	for _, item := range items {
		compact := map[string]any{}
		for k, v := range item {
			if keepFields[k] {
				compact[k] = v
			}
		}
		filtered = append(filtered, compact)
	}
	result, _ := json.Marshal(filtered)
	return result
}

// compactObjectFields strips known-verbose fields from single-object responses.
// Uses a blocklist so it works across all API domains.
func compactObjectFields(obj map[string]any) json.RawMessage {
	result, _ := json.Marshal(compactObjectMap(obj))
	return result
}

func compactObjectMap(obj map[string]any) map[string]any {
	stripFields := map[string]bool{
		"description": true, "body": true, "content": true,
		"comments": true, "attachments": true, "html": true, "markdown": true,
		"photo_urls": true, "photos": true, "images": true,
	}

	compact := map[string]any{}
	for k, v := range obj {
		if !stripFields[k] {
			compact[k] = v
		}
	}
	return compact
}

// printCSV renders JSON arrays as CSV with header row.
func printCSV(w io.Writer, data json.RawMessage) error {
	var items []map[string]any
	if err := json.Unmarshal(data, &items); err != nil || len(items) == 0 {
		// Single object or empty - just print as JSON
		fmt.Fprintln(w, string(data))
		return nil
	}
	// Collect all keys for header
	keySet := map[string]bool{}
	for _, item := range items {
		for k := range item {
			keySet[k] = true
		}
	}
	var keys []string
	for k := range keySet {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	// Header
	fmt.Fprintln(w, strings.Join(keys, ","))
	// Rows
	for _, item := range items {
		var vals []string
		for _, k := range keys {
			v := item[k]
			if v == nil {
				vals = append(vals, "")
			} else {
				s := fmt.Sprintf("%v", v)
				if strings.ContainsAny(s, ",\"\n") {
					s = `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
				}
				vals = append(vals, s)
			}
		}
		fmt.Fprintln(w, strings.Join(vals, ","))
	}
	return nil
}

type markdownEnvelope struct {
	Results any
	Meta    map[string]any
}

// printMarkdown renders JSON objects and arrays as Markdown. It is deliberately
// shape-aware rather than schema-bound: known Visor fields get useful ordering
// and sections, while unknown upstream fields still render through generic
// object/array fallbacks.
func printMarkdown(w io.Writer, data json.RawMessage) error {
	if env, ok := parseMarkdownEnvelope(data); ok {
		if err := printMarkdownAny(w, markdownTitle(env.Results, true), env.Results, 2); err != nil {
			return err
		}
		if len(env.Meta) > 0 {
			fmt.Fprintln(w)
			return printMarkdownAny(w, "Meta", env.Meta, 2)
		}
		return nil
	}

	var decoded any
	if err := json.Unmarshal(data, &decoded); err != nil {
		fmt.Fprintln(w, "```")
		fmt.Fprintln(w, string(data))
		fmt.Fprintln(w, "```")
		return nil
	}
	return printMarkdownAny(w, markdownTitle(decoded, true), decoded, 2)
}

func parseMarkdownEnvelope(data json.RawMessage) (markdownEnvelope, bool) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return markdownEnvelope{}, false
	}
	resultsRaw, hasResults := raw["results"]
	dataRaw, hasData := raw["data"]
	if !hasResults && !hasData {
		return markdownEnvelope{}, false
	}
	if !hasResults {
		resultsRaw = dataRaw
	}
	var results any
	if err := json.Unmarshal(resultsRaw, &results); err != nil {
		results = string(resultsRaw)
	}
	results = unwrapMarkdownData(results)
	meta := map[string]any{}
	if metaRaw, ok := raw["meta"]; ok {
		_ = json.Unmarshal(metaRaw, &meta)
	}
	return markdownEnvelope{Results: results, Meta: meta}, true
}

func unwrapMarkdownData(v any) any {
	obj, ok := v.(map[string]any)
	if !ok {
		return v
	}
	data, hasData := obj["data"]
	if !hasData {
		return v
	}
	// Only unwrap common response envelopes. If an upstream payload uses `data`
	// as one field among many domain fields, preserve the object.
	if len(obj) <= 3 {
		return data
	}
	if _, ok := obj["status"]; ok {
		return data
	}
	return v
}

func printMarkdownHeading(w io.Writer, title string) error {
	return printMarkdownHeadingLevel(w, 2, title)
}

func printMarkdownHeadingLevel(w io.Writer, level int, title string) error {
	if level < 1 {
		level = 1
	}
	if level > 6 {
		level = 6
	}
	_, err := fmt.Fprintf(w, "%s %s\n\n", strings.Repeat("#", level), title)
	return err
}

func printMarkdownTable(w io.Writer, items []map[string]any) error {
	if len(items) == 0 {
		_, err := fmt.Fprintln(w, "_No results._")
		return err
	}
	headers := markdownHeaders(items)
	fmt.Fprintf(w, "| %s |\n", strings.Join(headers, " | "))
	separators := make([]string, len(headers))
	for i := range separators {
		separators[i] = "---"
	}
	fmt.Fprintf(w, "| %s |\n", strings.Join(separators, " | "))
	for _, item := range items {
		row := make([]string, len(headers))
		for i, h := range headers {
			row[i] = markdownCellValue(h, item[h])
		}
		fmt.Fprintf(w, "| %s |\n", strings.Join(row, " | "))
	}
	return nil
}

func printMarkdownObject(w io.Writer, obj map[string]any) error {
	if len(obj) == 0 {
		_, err := fmt.Fprintln(w, "_No fields._")
		return err
	}
	headers := prioritizeAllHeaders(obj)
	fmt.Fprintln(w, "| Field | Value |")
	fmt.Fprintln(w, "| --- | --- |")
	for _, h := range headers {
		fmt.Fprintf(w, "| %s | %s |\n", escapeMarkdownTableCell(h), markdownCellValue(h, obj[h]))
	}
	return nil
}

func printMarkdownAny(w io.Writer, title string, v any, level int) error {
	v = unwrapMarkdownData(v)
	switch val := v.(type) {
	case []any:
		items, ok := markdownObjectArray(val)
		if ok {
			heading := markdownDisplayTitle(title, markdownTitle(items, false))
			if err := printMarkdownHeadingLevel(w, level, heading); err != nil {
				return err
			}
			fmt.Fprintf(w, "_%d result%s._\n\n", len(items), pluralSuffix(len(items)))
			return printMarkdownTable(w, items)
		}
		if err := printMarkdownHeadingLevel(w, level, title); err != nil {
			return err
		}
		return printMarkdownList(w, val)
	case map[string]any:
		return printMarkdownObjectSections(w, title, val, level)
	default:
		if err := printMarkdownHeadingLevel(w, level, title); err != nil {
			return err
		}
		_, err := fmt.Fprintf(w, "%s\n", escapeMarkdownText(formatCellValue(val)))
		return err
	}
}

func printMarkdownObjectSections(w io.Writer, title string, obj map[string]any, level int) error {
	if isFacetResponse(obj) {
		return printMarkdownFacets(w, obj, level)
	}
	if err := printMarkdownHeadingLevel(w, level, markdownDisplayTitle(title, markdownTitle(obj, false))); err != nil {
		return err
	}
	scalars, nested := splitMarkdownObject(obj)
	if len(scalars) == 0 && len(nested) == 0 {
		_, err := fmt.Fprintln(w, "_No fields._")
		return err
	}
	if len(scalars) > 0 {
		if len(nested) > 0 {
			if err := printMarkdownHeadingLevel(w, level+1, "Summary"); err != nil {
				return err
			}
		}
		if err := printMarkdownObject(w, scalars); err != nil {
			return err
		}
	}
	for _, key := range markdownNestedKeys(nested) {
		fmt.Fprintln(w)
		if err := printMarkdownAny(w, markdownHumanTitle(key), nested[key], level+1); err != nil {
			return err
		}
	}
	return nil
}

func printMarkdownFacets(w io.Writer, obj map[string]any, level int) error {
	if err := printMarkdownHeadingLevel(w, level, "Facets"); err != nil {
		return err
	}
	scalars, nested := splitMarkdownObject(obj)
	if len(scalars) > 0 {
		if err := printMarkdownHeadingLevel(w, level+1, "Summary"); err != nil {
			return err
		}
		if err := printMarkdownObject(w, scalars); err != nil {
			return err
		}
	}
	if stats, ok := nested["stats"]; ok {
		fmt.Fprintln(w)
		if err := printMarkdownAny(w, "Stats", stats, level+1); err != nil {
			return err
		}
		delete(nested, "stats")
	}
	if facets, ok := nested["facets"]; ok {
		fmt.Fprintln(w)
		if err := printMarkdownHeadingLevel(w, level+1, "Facet Values"); err != nil {
			return err
		}
		if err := printMarkdownFacetValues(w, facets, level+2); err != nil {
			return err
		}
		delete(nested, "facets")
	}
	for _, key := range markdownNestedKeys(nested) {
		fmt.Fprintln(w)
		if err := printMarkdownAny(w, markdownHumanTitle(key), nested[key], level+1); err != nil {
			return err
		}
	}
	return nil
}

func printMarkdownFacetValues(w io.Writer, facets any, level int) error {
	facetMap, ok := facets.(map[string]any)
	if !ok {
		return printMarkdownAny(w, "Facet Values", facets, level)
	}
	keys := make([]string, 0, len(facetMap))
	for key := range facetMap {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for i, key := range keys {
		if i > 0 {
			fmt.Fprintln(w)
		}
		if err := printMarkdownAny(w, markdownHumanTitle(key), facetMap[key], level); err != nil {
			return err
		}
	}
	return nil
}

func printMarkdownList(w io.Writer, items []any) error {
	if len(items) == 0 {
		_, err := fmt.Fprintln(w, "_No values._")
		return err
	}
	for _, item := range items {
		fmt.Fprintf(w, "- %s\n", escapeMarkdownText(formatCellValue(item)))
	}
	return nil
}

func markdownHeaders(items []map[string]any) []string {
	seen := map[string]bool{}
	headers := make([]string, 0)
	preferred := []string{
		"value", "count",
		"id", "listing_id", "vin", "year", "make", "model", "trim", "version",
		"price", "msrp", "miles", "dealer_id", "dealer_name", "city", "state",
		"postal_code", "inventory_type", "inventory_status", "vdp_url",
		"days_on_market", "distance", "exterior_color", "interior_color",
		"name", "title", "status", "type", "url", "created_at", "updated_at",
	}
	for _, h := range preferred {
		for _, item := range items {
			if _, ok := item[h]; ok && !seen[h] {
				seen[h] = true
				headers = append(headers, h)
				break
			}
		}
	}
	extra := make([]string, 0)
	for _, item := range items {
		for h := range item {
			if !seen[h] {
				seen[h] = true
				extra = append(extra, h)
			}
		}
	}
	sort.Strings(extra)
	headers = append(headers, extra...)
	return headers
}

func markdownObjectArray(items []any) ([]map[string]any, bool) {
	if len(items) == 0 {
		return []map[string]any{}, true
	}
	out := make([]map[string]any, 0, len(items))
	for _, item := range items {
		obj, ok := item.(map[string]any)
		if !ok {
			return nil, false
		}
		out = append(out, obj)
	}
	return out, true
}

func splitMarkdownObject(obj map[string]any) (map[string]any, map[string]any) {
	scalars := map[string]any{}
	nested := map[string]any{}
	for key, value := range obj {
		switch value.(type) {
		case map[string]any, []any:
			nested[key] = value
		default:
			scalars[key] = value
		}
	}
	return scalars, nested
}

func markdownNestedKeys(obj map[string]any) []string {
	preferred := []string{"stats", "facets", "latest_listing", "listing", "dealer", "build", "price_history", "options", "features"}
	seen := map[string]bool{}
	keys := make([]string, 0, len(obj))
	for _, key := range preferred {
		if _, ok := obj[key]; ok {
			seen[key] = true
			keys = append(keys, key)
		}
	}
	extra := make([]string, 0)
	for key := range obj {
		if !seen[key] {
			extra = append(extra, key)
		}
	}
	sort.Strings(extra)
	return append(keys, extra...)
}

func markdownTitle(v any, plural bool) string {
	switch val := v.(type) {
	case []map[string]any:
		if len(val) > 0 {
			return markdownRowTitle(val[0], true)
		}
	case []any:
		if items, ok := markdownObjectArray(val); ok && len(items) > 0 {
			return markdownRowTitle(items[0], true)
		}
	case map[string]any:
		if isFacetResponse(val) {
			return "Facets"
		}
		return markdownRowTitle(val, plural)
	}
	return "Results"
}

func markdownDisplayTitle(preferred, inferred string) string {
	if inferred != "" && inferred != "Results" {
		return inferred
	}
	if strings.TrimSpace(preferred) != "" {
		return preferred
	}
	return "Results"
}

func markdownRowTitle(obj map[string]any, plural bool) string {
	has := func(keys ...string) bool {
		for _, key := range keys {
			if _, ok := obj[key]; ok {
				return true
			}
		}
		return false
	}
	switch {
	case has("vin") && has("year", "make", "model", "price", "miles", "vdp_url"):
		if plural {
			return "Listings"
		}
		return "Vehicle"
	case has("vin"):
		if plural {
			return "Vehicles"
		}
		return "Vehicle"
	case has("dealer_id") || (has("name", "dealer_name") && has("city", "state")):
		if plural {
			return "Dealers"
		}
		return "Dealer"
	case has("command", "description", "score"):
		return "Commands"
	default:
		return "Results"
	}
}

func isFacetResponse(obj map[string]any) bool {
	_, hasFacets := obj["facets"]
	_, hasStats := obj["stats"]
	return hasFacets || hasStats
}

func markdownHumanTitle(key string) string {
	key = strings.TrimSpace(key)
	if key == "" {
		return "Values"
	}
	parts := strings.FieldsFunc(key, func(r rune) bool {
		return r == '_' || r == '-'
	})
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}

func pluralSuffix(count int) string {
	if count == 1 {
		return ""
	}
	return "s"
}

func markdownCellValue(field string, v any) string {
	if s, ok := v.(string); ok && isURLField(field) && isHTTPURL(s) {
		return fmt.Sprintf("[link](%s)", escapeMarkdownURL(s))
	}
	return escapeMarkdownTableCell(formatCellValue(v))
}

func isURLField(field string) bool {
	field = strings.ToLower(field)
	return field == "url" || strings.HasSuffix(field, "_url") || strings.HasSuffix(field, "url")
}

func isHTTPURL(s string) bool {
	return strings.HasPrefix(s, "https://") || strings.HasPrefix(s, "http://")
}

func escapeMarkdownURL(s string) string {
	s = strings.ReplaceAll(s, " ", "%20")
	s = strings.ReplaceAll(s, ")", "%29")
	return s
}

func escapeMarkdownText(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "`", "\\`")
	return s
}

func escapeMarkdownTableCell(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\r\n", "<br>")
	s = strings.ReplaceAll(s, "\n", "<br>")
	return s
}

// printOutput auto-detects arrays and renders as tables, or prints raw JSON for objects.
func printOutput(w io.Writer, data json.RawMessage, asJSON bool) error {
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}

	if asJSON {
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}

	// Try to detect if response is an array
	var items []map[string]any
	if err := json.Unmarshal(data, &items); err == nil && len(items) > 0 {
		if err := printAutoTable(w, items); err != nil {
			return err
		}
		// Agent-friendly: show count and suggest narrowing when results are large
		if len(items) >= 25 {
			fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
		}
		return nil
	}

	// Single object - pretty print
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err == nil {
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		return enc.Encode(obj)
	}

	// Fallback: print raw
	fmt.Fprintln(w, string(data))
	return nil
}

// levenshteinDistance computes the edit distance between two strings using a two-row DP approach.
func levenshteinDistance(a, b string) int {
	if len(a) == 0 {
		return len(b)
	}
	if len(b) == 0 {
		return len(a)
	}
	if len(a) < len(b) {
		a, b = b, a
	}
	prev := make([]int, len(b)+1)
	curr := make([]int, len(b)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(a); i++ {
		curr[0] = i
		for j := 1; j <= len(b); j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			ins := curr[j-1] + 1
			del := prev[j] + 1
			sub := prev[j-1] + cost
			min := ins
			if del < min {
				min = del
			}
			if sub < min {
				min = sub
			}
			curr[j] = min
		}
		prev, curr = curr, prev
	}
	return prev[len(b)]
}

// suggestFlag returns the closest known flag name to the unknown string, or "" if none is close enough.
func suggestFlag(unknown string, cmd *cobra.Command) string {
	unknown = strings.TrimLeft(unknown, "-")
	best := ""
	bestDist := 4 // only consider distance <= 3
	check := func(name string) {
		d := levenshteinDistance(unknown, name)
		if d < bestDist && d*5 <= len(unknown)*2 {
			bestDist = d
			best = name
		}
	}
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		check(f.Name)
	})
	cmd.InheritedFlags().VisitAll(func(f *pflag.Flag) {
		check(f.Name)
	})
	return best
}

// wantsHumanTable returns true when output should be a human-friendly table.
// Smart default: terminal=table, pipe=JSON.
// - Human in terminal: isTerminal()=true → table
// - Claude Code/Codex bash tool: stdout piped → JSON
// - --json/--csv/--markdown/--compact/--agent: explicit output format
func wantsHumanTable(w io.Writer, flags *rootFlags) bool {
	if flags.asJSON || flags.csv || flags.markdown || flags.compact || flags.quiet || flags.plain {
		return false
	}
	if flags.selectFields != "" {
		return false
	}
	return isTerminal(w)
}

func printAutoTable(w io.Writer, items []map[string]any) error {
	if len(items) == 0 {
		return nil
	}

	// Count scalar vs complex fields to decide format
	scalarCount := 0
	for _, v := range items[0] {
		switch v.(type) {
		case string, float64, bool, nil:
			scalarCount++
		}
	}

	// Use sectional/card layout for complex items (many fields or nested data)
	if len(items[0]) > 8 || scalarCount < len(items[0])-2 {
		return printAutoCards(w, items)
	}

	headers := prioritizeHeaders(items[0])

	// Limit to 6 columns max for readability
	if len(headers) > 6 {
		headers = headers[:6]
	}

	// Build rows
	rows := make([][]string, 0, len(items))
	for _, item := range items {
		row := make([]string, len(headers))
		for i, h := range headers {
			row[i] = formatCellValue(item[h])
		}
		rows = append(rows, row)
	}

	// Print with tab alignment using tabwriter
	tw := newTabWriter(w)
	upperHeaders := make([]string, len(headers))
	for i, h := range headers {
		upperHeaders[i] = bold(strings.ToUpper(h))
	}

	fmt.Fprintln(tw, strings.Join(upperHeaders, "\t"))
	for _, row := range rows {
		fmt.Fprintln(tw, strings.Join(row, "\t"))
	}
	return tw.Flush()
}

// prioritizeHeaders orders scalar fields by importance for table display.
func prioritizeHeaders(item map[string]any) []string {
	return prioritizeFields(item, false)
}

// prioritizeAllHeaders orders all fields (including arrays) by importance for card display.
func prioritizeAllHeaders(item map[string]any) []string {
	return prioritizeFields(item, true)
}

// prioritizeFields orders fields by importance: identity → temporal → status → other.
// When includeComplex is true, arrays and objects are included (for card layout).
//
// Uses exact-or-suffix matching to avoid false positives: "name" matches "Name" and
// "UserName" but not "BuildingName" (because "Building" is not a known prefix that
// indicates identity). The field is split on camelCase/snake_case boundaries and the
// LAST segment is matched against patterns.
func prioritizeFields(item map[string]any, includeComplex bool) []string {
	// Priority tiers — matched against the last segment of the field name.
	// "OrderDate" → last segment "date" → tier 1 (temporal).
	// "BuildingName" → last segment "name" → tier 0... but we want to avoid this.
	// Solution: exact match on the full lowered name OR suffix segment match,
	// with a penalty for compound names that have a non-identity prefix.
	type pattern struct {
		word string
		tier int
	}
	// Exact matches (full field name, case-insensitive) — highest confidence
	exactMatches := map[string]int{
		"id": 0, "name": 0, "title": 0, "slug": 0, "key": 0,
		"date": 1, "created": 1, "updated": 1, "createdat": 1, "updatedat": 1,
		"status": 2, "state": 2, "statuscode": 2,
		"summary": 3, "description": 3, "price": 3, "amount": 3, "total": 3,
		"cost": 3, "points": 3, "score": 3,
		"type": 4, "kind": 4, "category": 4, "email": 4, "phone": 4, "url": 4,
	}
	// Suffix patterns — match when the field ends with this word (after splitting)
	suffixMatches := map[string]int{
		"id": 0, "name": 0, "title": 0,
		"date": 1, "time": 1,
		"status": 2, "state": 2, "code": 2,
		"price": 3, "amount": 3, "total": 3, "cost": 3,
		"summary": 3, "description": 3, "points": 3, "score": 3,
		"type": 4, "kind": 4, "category": 4, "method": 4,
	}

	numTiers := 5

	type scored struct {
		name  string
		tier  int
		index int
	}

	var all []scored
	idx := 0
	for k, v := range item {
		if !includeComplex {
			switch v.(type) {
			case []any, map[string]any:
				continue
			}
		}
		// Skip values that won't render usefully in cards
		if includeComplex {
			formatted := formatCellValue(v)
			if formatted == "" {
				continue
			}
		}

		tier := numTiers // default: unclassified
		lower := strings.ToLower(k)

		// 1. Exact match on full field name
		if t, ok := exactMatches[lower]; ok {
			tier = t
		} else {
			// 2. Split camelCase into segments and match the last one
			segments := splitCamelCase(lower)
			if len(segments) > 0 {
				lastSeg := segments[len(segments)-1]
				if t, ok := suffixMatches[lastSeg]; ok {
					// Compound names with identity suffixes (BuildingName, TipTime)
					// get demoted one tier because the prefix dilutes the signal
					if len(segments) > 1 {
						tier = t + 1
					} else {
						tier = t
					}
				}
			}
		}

		// Demote booleans to last
		if _, ok := v.(bool); ok && tier >= numTiers {
			tier = numTiers + 1
		}
		all = append(all, scored{name: k, tier: tier, index: idx})
		idx++
	}

	sort.Slice(all, func(i, j int) bool {
		if all[i].tier != all[j].tier {
			return all[i].tier < all[j].tier
		}
		return all[i].index < all[j].index
	})

	headers := make([]string, len(all))
	for i, s := range all {
		headers[i] = s.name
	}
	return headers
}

// splitCamelCase splits "OrderDate" → ["order", "date"], "statusCode" → ["status", "code"],
// "page_size" → ["page", "size"].
func splitCamelCase(s string) []string {
	var segments []string
	var current strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if r == '_' || r == '-' {
			if current.Len() > 0 {
				segments = append(segments, current.String())
				current.Reset()
			}
			continue
		}
		if i > 0 && unicode.IsUpper(r) && unicode.IsLower(runes[i-1]) {
			if current.Len() > 0 {
				segments = append(segments, current.String())
				current.Reset()
			}
		}
		current.WriteRune(unicode.ToLower(r))
	}
	if current.Len() > 0 {
		segments = append(segments, current.String())
	}
	return segments
}

// printAutoCards renders items as labeled cards — one block per item.
// Used for complex responses with many fields or nested data.
func printAutoCards(w io.Writer, items []map[string]any) error {
	headers := prioritizeAllHeaders(items[0])

	// Find the longest header for alignment (from fields we'll actually show)
	maxLen := 0
	for _, h := range headers {
		if len(h) > maxLen {
			maxLen = len(h)
		}
	}

	for i, item := range items {
		if i > 0 {
			fmt.Fprintln(w)
		}

		// Card header: use first priority field as the card title
		titleVal := formatCellValue(item[headers[0]])
		if len(headers) > 1 {
			secondVal := formatCellValue(item[headers[1]])
			if secondVal != "" {
				fmt.Fprintf(w, "%s %s — %s\n", bold(strings.ToUpper(headers[0])), titleVal, secondVal)
			} else {
				fmt.Fprintf(w, "%s %s\n", bold(strings.ToUpper(headers[0])), titleVal)
			}
		} else {
			fmt.Fprintf(w, "%s %s\n", bold(strings.ToUpper(headers[0])), titleVal)
		}

		// Remaining fields indented — skip empty, zero, and false values
		for _, h := range headers[2:] {
			v := formatCellValue(item[h])
			if v == "" || v == "false" || v == "0" || v == "[]" || v == "null" {
				continue
			}
			// Multi-line values (nested arrays) start with \n
			if strings.HasPrefix(v, "\n") {
				fmt.Fprintf(w, "  %s:%s\n", h, v)
			} else {
				fmt.Fprintf(w, "  %-*s  %s\n", maxLen, h+":", v)
			}
		}
	}
	return nil
}

func formatCellValue(v any) string {
	switch val := v.(type) {
	case string:
		// Format ISO dates as just the date portion
		if len(val) >= 19 && val[4] == '-' && val[7] == '-' && val[10] == 'T' {
			return val[:10]
		}
		return truncate(val, 60)
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%.2f", val)
	case bool:
		return fmt.Sprintf("%t", val)
	case nil:
		return ""
	case []any:
		if len(val) == 0 {
			return ""
		}
		// If array contains objects, format each as a summary line
		if obj, isObj := val[0].(map[string]any); isObj {
			_ = obj
			return formatObjectArray(val)
		}
		// Flatten simple arrays into comma-separated string
		parts := make([]string, 0, len(val))
		for _, item := range val {
			if s, ok := item.(string); ok {
				parts = append(parts, s)
			} else {
				b, _ := json.Marshal(item)
				parts = append(parts, string(b))
			}
		}
		return truncate(strings.Join(parts, ", "), 60)
	case map[string]any:
		return formatSingleObject(val)
	default:
		b, _ := json.Marshal(val)
		return truncate(string(b), 60)
	}
}

// formatObjectArray renders an array of objects as multi-line summary.
// Each object is summarized by its most descriptive fields: name/title, qty, size, price.
func formatObjectArray(items []any) string {
	var lines []string
	for _, raw := range items {
		obj, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		lines = append(lines, formatObjectSummary(obj))
	}
	if len(lines) == 0 {
		return ""
	}
	// Multi-line: newline-prefixed so the card renderer can indent
	return "\n" + strings.Join(lines, "\n")
}

// formatObjectSummary extracts the most useful fields from an object into a one-line summary.
// Looks for: qty/count → name/title → size → price, in that order.
func formatObjectSummary(obj map[string]any) string {
	var parts []string

	// Quantity
	qty := findField(obj, "qty", "count", "quantity")
	if qty != "" && qty != "1" && qty != "0" {
		parts = append(parts, qty+"x")
	} else if qty == "1" {
		parts = append(parts, "1x")
	}

	// Name — check nested objects too (e.g., Side1.Name)
	name := findField(obj, "name", "title", "label", "description")
	if name == "" {
		// Check nested objects for name
		for _, key := range []string{"Side1", "side1", "Item", "item", "Product", "product"} {
			if nested, ok := obj[key].(map[string]any); ok {
				name = findField(nested, "name", "title", "label")
				if name != "" {
					break
				}
			}
		}
	}
	if name != "" {
		parts = append(parts, name)
	}

	// Size
	size := findField(obj, "sizename", "size_name")
	if size == "" {
		size = findField(obj, "catname", "cat_name", "category")
	}
	if size != "" {
		parts = append(parts, "—")
		parts = append(parts, size)
	}

	// Price
	price := findField(obj, "extprice", "price", "amount", "total")
	if price != "" && price != "0" {
		parts = append(parts, fmt.Sprintf("($%s)", price))
	}

	if len(parts) == 0 {
		// Fallback: JSON summary
		b, _ := json.Marshal(obj)
		return truncate(string(b), 80)
	}
	return "    " + strings.Join(parts, " ")
}

// formatSingleObject renders a single object by its most descriptive fields.
func formatSingleObject(obj map[string]any) string {
	name := findField(obj, "name", "title", "label", "description")
	if name != "" {
		return name
	}
	id := findField(obj, "id", "key", "code")
	if id != "" {
		return id
	}
	return ""
}

// findField searches an object for a field name (case-insensitive) and returns its formatted value.
func findField(obj map[string]any, names ...string) string {
	for _, name := range names {
		for k, v := range obj {
			if strings.EqualFold(k, name) {
				return formatCellValue(v)
			}
		}
	}
	return ""
}

// DataProvenance describes where data came from and when it was last synced.
type DataProvenance struct {
	Source       string     `json:"source"`                  // "live" or "local"
	SyncedAt     *time.Time `json:"synced_at,omitempty"`     // when local data was last synced
	Reason       string     `json:"reason,omitempty"`        // why local was used: "user_requested", "api_unreachable", "no_search_endpoint"
	ResourceType string     `json:"resource_type,omitempty"` // which resource type was queried
	Freshness    any        `json:"freshness,omitempty"`     // optional machine-owned freshness metadata for covered command paths
	Query        any        `json:"query,omitempty"`         // cleaned request query params for agent envelopes
}

// printProvenance writes a one-line provenance message to stderr for TTY users.
// Suppressed when stdout is piped or redirected — the JSON response envelope
// already carries meta.source, so the stderr line is redundant and becomes
// noise in agent flows that merge stderr into stdout.
func printProvenance(cmd *cobra.Command, count int, prov DataProvenance) {
	if !isTerminal(cmd.OutOrStdout()) {
		return
	}
	if prov.Source == "live" {
		fmt.Fprintf(cmd.ErrOrStderr(), "%d results (live)\n", count)
		return
	}
	age := "unknown"
	if prov.SyncedAt != nil {
		d := time.Since(*prov.SyncedAt)
		switch {
		case d < time.Minute:
			age = "just now"
		case d < time.Hour:
			age = fmt.Sprintf("%d minutes ago", int(d.Minutes()))
		case d < 24*time.Hour:
			age = fmt.Sprintf("%d hours ago", int(d.Hours()))
		default:
			age = fmt.Sprintf("%d days ago", int(d.Hours()/24))
		}
	}
	prefix := ""
	if prov.Reason == "api_unreachable" {
		prefix = "API unreachable. "
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "%s%d results (cached, synced %s)\n", prefix, count, age)
}

// wrapWithProvenance wraps response data in a provenance envelope:
// {"results": ..., "meta": {...}}. When data is valid JSON, it embeds as
// the parsed shape; when data is non-JSON (e.g., XML/RSS responses, plain
// text), it embeds as a JSON string so json.Marshal doesn't choke on
// "invalid character '<'" while still passing the raw payload through to
// the consumer.
func wrapWithProvenance(data json.RawMessage, prov DataProvenance) (json.RawMessage, error) {
	meta := map[string]any{"source": prov.Source}
	if prov.SyncedAt != nil {
		meta["synced_at"] = prov.SyncedAt.UTC().Format(time.RFC3339)
	}
	if prov.Reason != "" {
		meta["reason"] = prov.Reason
	}
	if prov.ResourceType != "" {
		meta["resource_type"] = prov.ResourceType
	}
	if prov.Freshness != nil {
		meta["freshness"] = prov.Freshness
	}
	if prov.Query != nil {
		meta["query"] = prov.Query
	}
	var results any = json.RawMessage(data)
	if !json.Valid(data) {
		results = string(data)
	}
	envelope := map[string]any{
		"results": results,
		"meta":    meta,
	}
	return json.Marshal(envelope)
}

// defaultDBPath returns the canonical path for the local SQLite database.
func defaultDBPath(name string) string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", name, "data.db")
}
