// Copyright 2026 Visor. Licensed under Apache-2.0. See LICENSE.
// Portions generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press).

package cli

import (
	"github.com/spf13/cobra"
)

func newListingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "listings",
		Short: "Manage listings",
	}

	cmd.AddCommand(newListingsGetCmd(flags))
	cmd.AddCommand(newListingsListCmd(flags))
	return cmd
}
