// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newListingsListCmd(flags *rootFlags) *cobra.Command {
	var flagLimit string
	var flagOffset string
	var flagSort string
	var flagMake string
	var flagModel string
	var flagTrim string
	var flagYear string
	var flagState string
	var flagDealerType string
	var flagInTransit string
	var flagInventoryType string
	var flagBodyType string
	var flagTransmission string
	var flagDrivetrain string
	var flagAssemblyLocation string
	var flagAssemblyCountry string
	var flagFuelType string
	var flagEngine string
	var flagVersion string
	var flagExteriorColor string
	var flagInteriorColor string
	var flagBaseExteriorColor string
	var flagBaseInteriorColor string
	var flagSeatingCapacity string
	var flagCylinders string
	var flagDoors string
	var flagOptionsPackages string
	var flagFeatures string
	var flagKeywords string
	var flagVinPattern string
	var flagExcludeMake string
	var flagExcludeModel string
	var flagExcludeTrim string
	var flagExcludeYear string
	var flagExcludeState string
	var flagExcludeVersion string
	var flagExcludeEngine string
	var flagExcludeAssemblyLocation string
	var flagExcludeAssemblyCountry string
	var flagExcludeExteriorColor string
	var flagExcludeInteriorColor string
	var flagExcludeBaseExteriorColor string
	var flagExcludeBaseInteriorColor string
	var flagExcludeOptionsPackages string
	var flagExcludeFeatures string
	var flagExcludeFuelType string
	var flagExcludePowertrainType string
	var flagExcludeKeywords string
	var flagInventoryStatus string
	var flagSoldWithinDays string
	var flagSnapshotDate string
	var flagMinPrice string
	var flagMaxPrice string
	var flagMinMileage string
	var flagMaxMileage string
	var flagMinMsrp string
	var flagMaxMsrp string
	var flagMinDaysOnMarket string
	var flagMaxDaysOnMarket string
	var flagLatitude string
	var flagLongitude string
	var flagPostalCode string
	var flagRadius string
	var flagBbox string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Returns active, sold, or historical snapshot listing summaries using stable snake_case fields. Public inventory is...",
		Example:     "  visor listings list",
		Annotations: map[string]string{"pp:endpoint": "listings.list", "pp:method": "GET", "pp:path": "/v1/listings", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"days_on_market", "-days_on_market", "price", "-price", "miles", "-miles", "msrp", "-msrp", "discount", "-discount", "distance"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			if cmd.Flags().Changed("in-transit") {
				allowedInTransit := []string{"true", "false"}
				validInTransit := false
				for _, v := range allowedInTransit {
					if flagInTransit == v {
						validInTransit = true
						break
					}
				}
				if !validInTransit {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "in-transit", flagInTransit, allowedInTransit)
				}
			}
			if cmd.Flags().Changed("inventory-status") {
				allowedInventoryStatus := []string{"active", "sold"}
				validInventoryStatus := false
				for _, v := range allowedInventoryStatus {
					if flagInventoryStatus == v {
						validInventoryStatus = true
						break
					}
				}
				if !validInventoryStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "inventory-status", flagInventoryStatus, allowedInventoryStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/listings"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "listings", path, map[string]string{
				"limit":                       fmt.Sprintf("%v", flagLimit),
				"offset":                      fmt.Sprintf("%v", flagOffset),
				"sort":                        fmt.Sprintf("%v", flagSort),
				"make":                        fmt.Sprintf("%v", flagMake),
				"model":                       fmt.Sprintf("%v", flagModel),
				"trim":                        fmt.Sprintf("%v", flagTrim),
				"year":                        fmt.Sprintf("%v", flagYear),
				"state":                       fmt.Sprintf("%v", flagState),
				"dealer_type":                 fmt.Sprintf("%v", flagDealerType),
				"in_transit":                  fmt.Sprintf("%v", flagInTransit),
				"inventory_type":              fmt.Sprintf("%v", flagInventoryType),
				"body_type":                   fmt.Sprintf("%v", flagBodyType),
				"transmission":                fmt.Sprintf("%v", flagTransmission),
				"drivetrain":                  fmt.Sprintf("%v", flagDrivetrain),
				"assembly_location":           fmt.Sprintf("%v", flagAssemblyLocation),
				"assembly_country":            fmt.Sprintf("%v", flagAssemblyCountry),
				"fuel_type":                   fmt.Sprintf("%v", flagFuelType),
				"engine":                      fmt.Sprintf("%v", flagEngine),
				"version":                     fmt.Sprintf("%v", flagVersion),
				"exterior_color":              fmt.Sprintf("%v", flagExteriorColor),
				"interior_color":              fmt.Sprintf("%v", flagInteriorColor),
				"base_exterior_color":         fmt.Sprintf("%v", flagBaseExteriorColor),
				"base_interior_color":         fmt.Sprintf("%v", flagBaseInteriorColor),
				"seating_capacity":            fmt.Sprintf("%v", flagSeatingCapacity),
				"cylinders":                   fmt.Sprintf("%v", flagCylinders),
				"doors":                       fmt.Sprintf("%v", flagDoors),
				"options_packages":            fmt.Sprintf("%v", flagOptionsPackages),
				"features":                    fmt.Sprintf("%v", flagFeatures),
				"keywords":                    fmt.Sprintf("%v", flagKeywords),
				"vin_pattern":                 fmt.Sprintf("%v", flagVinPattern),
				"exclude_make":                fmt.Sprintf("%v", flagExcludeMake),
				"exclude_model":               fmt.Sprintf("%v", flagExcludeModel),
				"exclude_trim":                fmt.Sprintf("%v", flagExcludeTrim),
				"exclude_year":                fmt.Sprintf("%v", flagExcludeYear),
				"exclude_state":               fmt.Sprintf("%v", flagExcludeState),
				"exclude_version":             fmt.Sprintf("%v", flagExcludeVersion),
				"exclude_engine":              fmt.Sprintf("%v", flagExcludeEngine),
				"exclude_assembly_location":   fmt.Sprintf("%v", flagExcludeAssemblyLocation),
				"exclude_assembly_country":    fmt.Sprintf("%v", flagExcludeAssemblyCountry),
				"exclude_exterior_color":      fmt.Sprintf("%v", flagExcludeExteriorColor),
				"exclude_interior_color":      fmt.Sprintf("%v", flagExcludeInteriorColor),
				"exclude_base_exterior_color": fmt.Sprintf("%v", flagExcludeBaseExteriorColor),
				"exclude_base_interior_color": fmt.Sprintf("%v", flagExcludeBaseInteriorColor),
				"exclude_options_packages":    fmt.Sprintf("%v", flagExcludeOptionsPackages),
				"exclude_features":            fmt.Sprintf("%v", flagExcludeFeatures),
				"exclude_fuel_type":           fmt.Sprintf("%v", flagExcludeFuelType),
				"exclude_powertrain_type":     fmt.Sprintf("%v", flagExcludePowertrainType),
				"exclude_keywords":            fmt.Sprintf("%v", flagExcludeKeywords),
				"inventory_status":            fmt.Sprintf("%v", flagInventoryStatus),
				"sold_within_days":            fmt.Sprintf("%v", flagSoldWithinDays),
				"snapshot_date":               fmt.Sprintf("%v", flagSnapshotDate),
				"min_price":                   fmt.Sprintf("%v", flagMinPrice),
				"max_price":                   fmt.Sprintf("%v", flagMaxPrice),
				"min_mileage":                 fmt.Sprintf("%v", flagMinMileage),
				"max_mileage":                 fmt.Sprintf("%v", flagMaxMileage),
				"min_msrp":                    fmt.Sprintf("%v", flagMinMsrp),
				"max_msrp":                    fmt.Sprintf("%v", flagMaxMsrp),
				"min_days_on_market":          fmt.Sprintf("%v", flagMinDaysOnMarket),
				"max_days_on_market":          fmt.Sprintf("%v", flagMaxDaysOnMarket),
				"latitude":                    fmt.Sprintf("%v", flagLatitude),
				"longitude":                   fmt.Sprintf("%v", flagLongitude),
				"postal_code":                 fmt.Sprintf("%v", flagPostalCode),
				"radius":                      fmt.Sprintf("%v", flagRadius),
				"bbox":                        fmt.Sprintf("%v", flagBbox),
			}, nil, flagAll, "offset", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance first so --select paths match
			// the documented envelope shape, e.g. results.data.vin.
			if flags.asJSON || flags.markdown || !isTerminal(cmd.OutOrStdout()) {
				wrapped, wrapErr := wrapWithProvenance(data, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutputWithFlags(cmd.OutOrStdout(), wrapped, flags)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Page size as an integer string. Defaults to 50; maximum 100.")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "Zero-based page offset as an integer string. Defaults to 0.")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort order. Use field names with optional - for descending, for example price or -price. Defaults to days_on_market,... (one of: days_on_market, -days_on_market, price, -price, miles, -miles, msrp, -msrp, discount, -discount, distance)")
	cmd.Flags().StringVar(&flagMake, "make", "", "Comma-separated make names or slugs, for example toyota,honda.")
	cmd.Flags().StringVar(&flagModel, "model", "", "Comma-separated model names or slugs. Combine with make when possible for narrower results.")
	cmd.Flags().StringVar(&flagTrim, "trim", "", "Comma-separated trim names.")
	cmd.Flags().StringVar(&flagYear, "year", "", "Comma-separated model years, for example 2023,2024.")
	cmd.Flags().StringVar(&flagState, "state", "", "Comma-separated two-letter dealer states, for example CA,TX.")
	cmd.Flags().StringVar(&flagDealerType, "dealer-type", "", "Comma-separated dealer types, for example franchise,independent.")
	cmd.Flags().StringVar(&flagInTransit, "in-transit", "", "Whether to return in-transit/build inventory or only stock inventory. (one of: true, false)")
	cmd.Flags().StringVar(&flagInventoryType, "inventory-type", "", "Comma-separated inventory classes such as new,used,certified.")
	cmd.Flags().StringVar(&flagBodyType, "body-type", "", "Comma-separated body types.")
	cmd.Flags().StringVar(&flagTransmission, "transmission", "", "Comma-separated transmission values.")
	cmd.Flags().StringVar(&flagDrivetrain, "drivetrain", "", "Comma-separated drivetrain values.")
	cmd.Flags().StringVar(&flagAssemblyLocation, "assembly-location", "", "Pipe-separated assembly locations. Uses | because locations often contain commas.")
	cmd.Flags().StringVar(&flagAssemblyCountry, "assembly-country", "", "Comma-separated assembly country values.")
	cmd.Flags().StringVar(&flagFuelType, "fuel-type", "", "Comma-separated fuel type values.")
	cmd.Flags().StringVar(&flagEngine, "engine", "", "Comma-separated engine descriptions.")
	cmd.Flags().StringVar(&flagVersion, "version", "", "Comma-separated vehicle version values.")
	cmd.Flags().StringVar(&flagExteriorColor, "exterior-color", "", "Comma-separated exterior color values.")
	cmd.Flags().StringVar(&flagInteriorColor, "interior-color", "", "Comma-separated interior color values.")
	cmd.Flags().StringVar(&flagBaseExteriorColor, "base-exterior-color", "", "Comma-separated normalized exterior color values.")
	cmd.Flags().StringVar(&flagBaseInteriorColor, "base-interior-color", "", "Comma-separated normalized interior color values.")
	cmd.Flags().StringVar(&flagSeatingCapacity, "seating-capacity", "", "Comma-separated seating capacity integers.")
	cmd.Flags().StringVar(&flagCylinders, "cylinders", "", "Comma-separated cylinder count integers.")
	cmd.Flags().StringVar(&flagDoors, "doors", "", "Comma-separated door count integers.")
	cmd.Flags().StringVar(&flagOptionsPackages, "options-packages", "", "Comma-separated manufacturer option/package codes.")
	cmd.Flags().StringVar(&flagFeatures, "features", "", "Comma-separated feature tokens.")
	cmd.Flags().StringVar(&flagKeywords, "keywords", "", "Comma-separated listing keyword tokens. Positive tokens must be present; negative history tokens are excluded.")
	cmd.Flags().StringVar(&flagVinPattern, "vin-pattern", "", "Comma-separated VIN masks, up to 10 distinct patterns. VIN characters match themselves, ? matches one VIN position,...")
	cmd.Flags().StringVar(&flagExcludeMake, "exclude-make", "", "Comma-separated makes to exclude.")
	cmd.Flags().StringVar(&flagExcludeModel, "exclude-model", "", "Comma-separated models to exclude.")
	cmd.Flags().StringVar(&flagExcludeTrim, "exclude-trim", "", "Comma-separated trims to exclude.")
	cmd.Flags().StringVar(&flagExcludeYear, "exclude-year", "", "Comma-separated model years to exclude.")
	cmd.Flags().StringVar(&flagExcludeState, "exclude-state", "", "Comma-separated dealer states to exclude.")
	cmd.Flags().StringVar(&flagExcludeVersion, "exclude-version", "", "Comma-separated vehicle versions to exclude.")
	cmd.Flags().StringVar(&flagExcludeEngine, "exclude-engine", "", "Comma-separated engine descriptions to exclude.")
	cmd.Flags().StringVar(&flagExcludeAssemblyLocation, "exclude-assembly-location", "", "Plus-separated assembly locations to exclude. Uses + to match the private API separator.")
	cmd.Flags().StringVar(&flagExcludeAssemblyCountry, "exclude-assembly-country", "", "Comma-separated assembly countries to exclude.")
	cmd.Flags().StringVar(&flagExcludeExteriorColor, "exclude-exterior-color", "", "Comma-separated exterior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeInteriorColor, "exclude-interior-color", "", "Comma-separated interior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeBaseExteriorColor, "exclude-base-exterior-color", "", "Comma-separated normalized exterior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeBaseInteriorColor, "exclude-base-interior-color", "", "Comma-separated normalized interior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeOptionsPackages, "exclude-options-packages", "", "Comma-separated manufacturer option/package codes to exclude.")
	cmd.Flags().StringVar(&flagExcludeFeatures, "exclude-features", "", "Comma-separated feature tokens to exclude.")
	cmd.Flags().StringVar(&flagExcludeFuelType, "exclude-fuel-type", "", "Comma-separated fuel types to exclude.")
	cmd.Flags().StringVar(&flagExcludePowertrainType, "exclude-powertrain-type", "", "Comma-separated powertrain types to exclude.")
	cmd.Flags().StringVar(&flagExcludeKeywords, "exclude-keywords", "", "Comma-separated keyword tokens to exclude.")
	cmd.Flags().StringVar(&flagInventoryStatus, "inventory-status", "", "Inventory mode. active is the default; sold searches historical sold inventory. (one of: active, sold)")
	cmd.Flags().StringVar(&flagSoldWithinDays, "sold-within-days", "", "Positive integer day window for sold inventory, for example 30. Cannot be combined with snapshot_date.")
	cmd.Flags().StringVar(&flagSnapshotDate, "snapshot-date", "", "Historical active-inventory snapshot date in YYYY-MM-DD format. Cannot be combined with sold inventory filters.")
	cmd.Flags().StringVar(&flagMinPrice, "min-price", "", "Minimum listed price in whole dollars.")
	cmd.Flags().StringVar(&flagMaxPrice, "max-price", "", "Maximum listed price in whole dollars.")
	cmd.Flags().StringVar(&flagMinMileage, "min-mileage", "", "Minimum odometer mileage.")
	cmd.Flags().StringVar(&flagMaxMileage, "max-mileage", "", "Maximum odometer mileage.")
	cmd.Flags().StringVar(&flagMinMsrp, "min-msrp", "", "Minimum combined MSRP in whole dollars.")
	cmd.Flags().StringVar(&flagMaxMsrp, "max-msrp", "", "Maximum combined MSRP in whole dollars.")
	cmd.Flags().StringVar(&flagMinDaysOnMarket, "min-days-on-market", "", "Minimum days on market.")
	cmd.Flags().StringVar(&flagMaxDaysOnMarket, "max-days-on-market", "", "Maximum days on market.")
	cmd.Flags().StringVar(&flagLatitude, "latitude", "", "Search origin latitude for sort=distance, distance_miles, and radius filtering.")
	cmd.Flags().StringVar(&flagLongitude, "longitude", "", "Search origin longitude for sort=distance, distance_miles, and radius filtering.")
	cmd.Flags().StringVar(&flagPostalCode, "postal-code", "", "US ZIP/postal search origin for sort=distance, distance_miles, and radius filtering.")
	cmd.Flags().StringVar(&flagRadius, "radius", "", "Maximum distance from the search origin, in miles. Requires postal_code or latitude and longitude. Maximum 500.")
	cmd.Flags().StringVar(&flagBbox, "bbox", "", "Map viewport as west,south,east,north. Cannot be combined with radius. Maximum diagonal is 1000 miles.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
