// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUsagePromotedCmd(flags *rootFlags) *cobra.Command {
	var flagStartDate string
	var flagEndDate string
	var flagMeteringClass string

	cmd := &cobra.Command{
		Use:         "usage",
		Short:       "Returns daily billable usage totals for the authenticated API account. Usage analytics are eventually consistent...",
		Long:        "Returns daily billable usage totals for the authenticated API account. Usage analytics are eventually consistent...",
		Example:     "  visor usage",
		Annotations: map[string]string{"pp:endpoint": "usage.public", "pp:method": "GET", "pp:path": "/v1/usage", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/usage"
			params := map[string]string{}
			if flagStartDate != "" {
				params["start_date"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagEndDate != "" {
				params["end_date"] = fmt.Sprintf("%v", flagEndDate)
			}
			if flagMeteringClass != "" {
				params["metering_class"] = fmt.Sprintf("%v", flagMeteringClass)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "usage", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For structured output, wrap with provenance first so --select paths
			// match the documented envelope shape, e.g. results.data.vin.
			if flags.asJSON || flags.markdown || !isTerminal(cmd.OutOrStdout()) {
				wrapped, wrapErr := wrapWithProvenance(data, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutputWithFlags(cmd.OutOrStdout(), wrapped, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Inclusive UTC start date in YYYY-MM-DD format. Defaults to 29 days before end_date.")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Inclusive UTC end date in YYYY-MM-DD format. Defaults to today.")
	cmd.Flags().StringVar(&flagMeteringClass, "metering-class", "", "Optional comma-separated metering classes to include.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
