// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFacetsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagFacets string
	var flagFacetValueLimit string
	var flagMetric string
	var flagSort string
	var flagMake string
	var flagModel string
	var flagTrim string
	var flagYear string
	var flagState string
	var flagDealerId string
	var flagDealerType string
	var flagAvailabilityStatus string
	var flagInventoryType string
	var flagBodyType string
	var flagTransmission string
	var flagDrivetrain string
	var flagAssemblyLocation string
	var flagAssemblyCountry string
	var flagFuelType string
	var flagPowertrainType string
	var flagEngine string
	var flagVersion string
	var flagExteriorColor string
	var flagInteriorColor string
	var flagBaseExteriorColor string
	var flagBaseInteriorColor string
	var flagSeatingCapacity string
	var flagCylinders string
	var flagDoors string
	var flagOptionsPackages string
	var flagFeatures string
	var flagKeywords string
	var flagVinPattern string
	var flagExcludeMake string
	var flagExcludeModel string
	var flagExcludeTrim string
	var flagExcludeYear string
	var flagExcludeState string
	var flagExcludeInventoryType string
	var flagExcludeBodyType string
	var flagExcludeTransmission string
	var flagExcludeDrivetrain string
	var flagExcludeVersion string
	var flagExcludeEngine string
	var flagExcludeAssemblyLocation string
	var flagExcludeAssemblyCountry string
	var flagExcludeExteriorColor string
	var flagExcludeInteriorColor string
	var flagExcludeBaseExteriorColor string
	var flagExcludeBaseInteriorColor string
	var flagExcludeOptionsPackages string
	var flagExcludeFeatures string
	var flagExcludeFuelType string
	var flagExcludePowertrainType string
	var flagExcludeKeywords string
	var flagInventoryStatus string
	var flagSoldWithinDays string
	var flagSnapshotDate string
	var flagMinPrice string
	var flagMaxPrice string
	var flagMinMileage string
	var flagMaxMileage string
	var flagMinMsrp string
	var flagMaxMsrp string
	var flagMinDaysOnMarket string
	var flagMaxDaysOnMarket string
	var flagLatitude string
	var flagLongitude string
	var flagPostalCode string
	var flagRadius string
	var flagBbox string

	cmd := &cobra.Command{
		Use:         "facets",
		Short:       "Returns categorical facets, numeric range facets, and stats for an explicit listing filter surface facet selection....",
		Long:        "Shortcut for 'facets list'. Returns categorical facets, numeric range facets, and stats for an explicit listing filter surface facet selection....",
		Example:     "  visor facets --facets example-value",
		Annotations: map[string]string{"pp:endpoint": "facets.list", "pp:method": "GET", "pp:path": "/v1/facets", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("facets") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "facets")
			}
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"count", "-count", "metric", "-metric"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			if cmd.Flags().Changed("inventory-status") {
				allowedInventoryStatus := []string{"active", "sold"}
				validInventoryStatus := false
				for _, v := range allowedInventoryStatus {
					if flagInventoryStatus == v {
						validInventoryStatus = true
						break
					}
				}
				if !validInventoryStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "inventory-status", flagInventoryStatus, allowedInventoryStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/facets"
			params := map[string]string{}
			if flagFacets != "" {
				params["facets"] = fmt.Sprintf("%v", flagFacets)
			}
			if flagFacetValueLimit != "" {
				params["facet_value_limit"] = fmt.Sprintf("%v", flagFacetValueLimit)
			}
			if flagMetric != "" {
				params["metric"] = fmt.Sprintf("%v", flagMetric)
			}
			if flagSort != "" {
				params["sort"] = fmt.Sprintf("%v", flagSort)
			}
			if flagMake != "" {
				params["make"] = fmt.Sprintf("%v", flagMake)
			}
			if flagModel != "" {
				params["model"] = fmt.Sprintf("%v", flagModel)
			}
			if flagTrim != "" {
				params["trim"] = fmt.Sprintf("%v", flagTrim)
			}
			if flagYear != "" {
				params["year"] = fmt.Sprintf("%v", flagYear)
			}
			if flagState != "" {
				params["state"] = fmt.Sprintf("%v", flagState)
			}
			if flagDealerId != "" {
				params["dealer_id"] = fmt.Sprintf("%v", flagDealerId)
			}
			if flagDealerType != "" {
				params["dealer_type"] = fmt.Sprintf("%v", flagDealerType)
			}
			if flagAvailabilityStatus != "" {
				params["availability_status"] = fmt.Sprintf("%v", flagAvailabilityStatus)
			}
			if flagInventoryType != "" {
				params["inventory_type"] = fmt.Sprintf("%v", flagInventoryType)
			}
			if flagBodyType != "" {
				params["body_type"] = fmt.Sprintf("%v", flagBodyType)
			}
			if flagTransmission != "" {
				params["transmission"] = fmt.Sprintf("%v", flagTransmission)
			}
			if flagDrivetrain != "" {
				params["drivetrain"] = fmt.Sprintf("%v", flagDrivetrain)
			}
			if flagAssemblyLocation != "" {
				params["assembly_location"] = fmt.Sprintf("%v", flagAssemblyLocation)
			}
			if flagAssemblyCountry != "" {
				params["assembly_country"] = fmt.Sprintf("%v", flagAssemblyCountry)
			}
			if flagFuelType != "" {
				params["fuel_type"] = fmt.Sprintf("%v", flagFuelType)
			}
			if flagPowertrainType != "" {
				params["powertrain_type"] = fmt.Sprintf("%v", flagPowertrainType)
			}
			if flagEngine != "" {
				params["engine"] = fmt.Sprintf("%v", flagEngine)
			}
			if flagVersion != "" {
				params["version"] = fmt.Sprintf("%v", flagVersion)
			}
			if flagExteriorColor != "" {
				params["exterior_color"] = fmt.Sprintf("%v", flagExteriorColor)
			}
			if flagInteriorColor != "" {
				params["interior_color"] = fmt.Sprintf("%v", flagInteriorColor)
			}
			if flagBaseExteriorColor != "" {
				params["base_exterior_color"] = fmt.Sprintf("%v", flagBaseExteriorColor)
			}
			if flagBaseInteriorColor != "" {
				params["base_interior_color"] = fmt.Sprintf("%v", flagBaseInteriorColor)
			}
			if flagSeatingCapacity != "" {
				params["seating_capacity"] = fmt.Sprintf("%v", flagSeatingCapacity)
			}
			if flagCylinders != "" {
				params["cylinders"] = fmt.Sprintf("%v", flagCylinders)
			}
			if flagDoors != "" {
				params["doors"] = fmt.Sprintf("%v", flagDoors)
			}
			if flagOptionsPackages != "" {
				params["options_packages"] = fmt.Sprintf("%v", flagOptionsPackages)
			}
			if flagFeatures != "" {
				params["features"] = fmt.Sprintf("%v", flagFeatures)
			}
			if flagKeywords != "" {
				params["keywords"] = fmt.Sprintf("%v", flagKeywords)
			}
			if flagVinPattern != "" {
				params["vin_pattern"] = fmt.Sprintf("%v", flagVinPattern)
			}
			if flagExcludeMake != "" {
				params["exclude_make"] = fmt.Sprintf("%v", flagExcludeMake)
			}
			if flagExcludeModel != "" {
				params["exclude_model"] = fmt.Sprintf("%v", flagExcludeModel)
			}
			if flagExcludeTrim != "" {
				params["exclude_trim"] = fmt.Sprintf("%v", flagExcludeTrim)
			}
			if flagExcludeYear != "" {
				params["exclude_year"] = fmt.Sprintf("%v", flagExcludeYear)
			}
			if flagExcludeState != "" {
				params["exclude_state"] = fmt.Sprintf("%v", flagExcludeState)
			}
			if flagExcludeInventoryType != "" {
				params["exclude_inventory_type"] = fmt.Sprintf("%v", flagExcludeInventoryType)
			}
			if flagExcludeBodyType != "" {
				params["exclude_body_type"] = fmt.Sprintf("%v", flagExcludeBodyType)
			}
			if flagExcludeTransmission != "" {
				params["exclude_transmission"] = fmt.Sprintf("%v", flagExcludeTransmission)
			}
			if flagExcludeDrivetrain != "" {
				params["exclude_drivetrain"] = fmt.Sprintf("%v", flagExcludeDrivetrain)
			}
			if flagExcludeVersion != "" {
				params["exclude_version"] = fmt.Sprintf("%v", flagExcludeVersion)
			}
			if flagExcludeEngine != "" {
				params["exclude_engine"] = fmt.Sprintf("%v", flagExcludeEngine)
			}
			if flagExcludeAssemblyLocation != "" {
				params["exclude_assembly_location"] = fmt.Sprintf("%v", flagExcludeAssemblyLocation)
			}
			if flagExcludeAssemblyCountry != "" {
				params["exclude_assembly_country"] = fmt.Sprintf("%v", flagExcludeAssemblyCountry)
			}
			if flagExcludeExteriorColor != "" {
				params["exclude_exterior_color"] = fmt.Sprintf("%v", flagExcludeExteriorColor)
			}
			if flagExcludeInteriorColor != "" {
				params["exclude_interior_color"] = fmt.Sprintf("%v", flagExcludeInteriorColor)
			}
			if flagExcludeBaseExteriorColor != "" {
				params["exclude_base_exterior_color"] = fmt.Sprintf("%v", flagExcludeBaseExteriorColor)
			}
			if flagExcludeBaseInteriorColor != "" {
				params["exclude_base_interior_color"] = fmt.Sprintf("%v", flagExcludeBaseInteriorColor)
			}
			if flagExcludeOptionsPackages != "" {
				params["exclude_options_packages"] = fmt.Sprintf("%v", flagExcludeOptionsPackages)
			}
			if flagExcludeFeatures != "" {
				params["exclude_features"] = fmt.Sprintf("%v", flagExcludeFeatures)
			}
			if flagExcludeFuelType != "" {
				params["exclude_fuel_type"] = fmt.Sprintf("%v", flagExcludeFuelType)
			}
			if flagExcludePowertrainType != "" {
				params["exclude_powertrain_type"] = fmt.Sprintf("%v", flagExcludePowertrainType)
			}
			if flagExcludeKeywords != "" {
				params["exclude_keywords"] = fmt.Sprintf("%v", flagExcludeKeywords)
			}
			if flagInventoryStatus != "" {
				params["inventory_status"] = fmt.Sprintf("%v", flagInventoryStatus)
			}
			if flagSoldWithinDays != "" {
				params["sold_within_days"] = fmt.Sprintf("%v", flagSoldWithinDays)
			}
			if flagSnapshotDate != "" {
				params["snapshot_date"] = fmt.Sprintf("%v", flagSnapshotDate)
			}
			if flagMinPrice != "" {
				params["min_price"] = fmt.Sprintf("%v", flagMinPrice)
			}
			if flagMaxPrice != "" {
				params["max_price"] = fmt.Sprintf("%v", flagMaxPrice)
			}
			if flagMinMileage != "" {
				params["min_mileage"] = fmt.Sprintf("%v", flagMinMileage)
			}
			if flagMaxMileage != "" {
				params["max_mileage"] = fmt.Sprintf("%v", flagMaxMileage)
			}
			if flagMinMsrp != "" {
				params["min_msrp"] = fmt.Sprintf("%v", flagMinMsrp)
			}
			if flagMaxMsrp != "" {
				params["max_msrp"] = fmt.Sprintf("%v", flagMaxMsrp)
			}
			if flagMinDaysOnMarket != "" {
				params["min_days_on_market"] = fmt.Sprintf("%v", flagMinDaysOnMarket)
			}
			if flagMaxDaysOnMarket != "" {
				params["max_days_on_market"] = fmt.Sprintf("%v", flagMaxDaysOnMarket)
			}
			if flagLatitude != "" {
				params["latitude"] = fmt.Sprintf("%v", flagLatitude)
			}
			if flagLongitude != "" {
				params["longitude"] = fmt.Sprintf("%v", flagLongitude)
			}
			if flagPostalCode != "" {
				params["postal_code"] = fmt.Sprintf("%v", flagPostalCode)
			}
			if flagRadius != "" {
				params["radius"] = fmt.Sprintf("%v", flagRadius)
			}
			if flagBbox != "" {
				params["bbox"] = fmt.Sprintf("%v", flagBbox)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "facets", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For structured output, wrap with provenance first so --select paths
			// match the documented envelope shape, e.g. results.data.vin.
			if flags.asJSON || flags.markdown || !isTerminal(cmd.OutOrStdout()) {
				wrapped, wrapErr := wrapWithProvenance(data, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutputWithFlags(cmd.OutOrStdout(), wrapped, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagFacets, "facets", "", "Required comma-separated facet names to return. Supported facets: make, model, inventory_type, year, trim, version,...")
	cmd.Flags().StringVar(&flagFacetValueLimit, "facet-value-limit", "", "Maximum number of values returned per categorical facet. Defaults to 20; maximum 100. Numeric range facets always...")
	cmd.Flags().StringVar(&flagMetric, "metric", "", "Facet Metric used to compute an optional per-bucket aggregate. Defaults to count. Supported measures: price, miles,...")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Facet bucket ordering. Defaults to -count. Sorting by metric requires a non-count metric. (one of: count, -count, metric, -metric)")
	cmd.Flags().StringVar(&flagMake, "make", "", "Comma-separated make names or slugs to apply before counting facet buckets.")
	cmd.Flags().StringVar(&flagModel, "model", "", "Comma-separated model names or slugs to apply before counting facet buckets.")
	cmd.Flags().StringVar(&flagTrim, "trim", "", "Comma-separated trim names to apply before counting facet buckets.")
	cmd.Flags().StringVar(&flagYear, "year", "", "Comma-separated model years to apply before counting facet buckets.")
	cmd.Flags().StringVar(&flagState, "state", "", "Comma-separated two-letter dealer states to apply before counting facet buckets.")
	cmd.Flags().StringVar(&flagDealerId, "dealer-id", "", "Comma-separated dealer UUIDs to apply before counting facet buckets. Accepts up to 50 dealer IDs.")
	cmd.Flags().StringVar(&flagDealerType, "dealer-type", "", "Comma-separated dealer types to apply before counting facet buckets.")
	cmd.Flags().StringVar(&flagAvailabilityStatus, "availability-status", "", "Comma-separated availability statuses to apply before counting facet buckets: stock, transit, build.")
	cmd.Flags().StringVar(&flagInventoryType, "inventory-type", "", "Comma-separated inventory classes to apply before counting facet buckets: new, used, certified. cpo is accepted as...")
	cmd.Flags().StringVar(&flagBodyType, "body-type", "", "Comma-separated body types.")
	cmd.Flags().StringVar(&flagTransmission, "transmission", "", "Comma-separated transmission values.")
	cmd.Flags().StringVar(&flagDrivetrain, "drivetrain", "", "Comma-separated drivetrain values.")
	cmd.Flags().StringVar(&flagAssemblyLocation, "assembly-location", "", "Pipe-separated assembly locations. Uses | because locations often contain commas.")
	cmd.Flags().StringVar(&flagAssemblyCountry, "assembly-country", "", "Comma-separated assembly country values.")
	cmd.Flags().StringVar(&flagFuelType, "fuel-type", "", "Comma-separated fuel type values.")
	cmd.Flags().StringVar(&flagPowertrainType, "powertrain-type", "", "Comma-separated powertrain type values.")
	cmd.Flags().StringVar(&flagEngine, "engine", "", "Comma-separated engine descriptions.")
	cmd.Flags().StringVar(&flagVersion, "version", "", "Comma-separated vehicle version values.")
	cmd.Flags().StringVar(&flagExteriorColor, "exterior-color", "", "Comma-separated exterior color values.")
	cmd.Flags().StringVar(&flagInteriorColor, "interior-color", "", "Comma-separated interior color values.")
	cmd.Flags().StringVar(&flagBaseExteriorColor, "base-exterior-color", "", "Comma-separated normalized exterior color values.")
	cmd.Flags().StringVar(&flagBaseInteriorColor, "base-interior-color", "", "Comma-separated normalized interior color values.")
	cmd.Flags().StringVar(&flagSeatingCapacity, "seating-capacity", "", "Comma-separated seating capacity integers.")
	cmd.Flags().StringVar(&flagCylinders, "cylinders", "", "Comma-separated cylinder count integers.")
	cmd.Flags().StringVar(&flagDoors, "doors", "", "Comma-separated door count integers.")
	cmd.Flags().StringVar(&flagOptionsPackages, "options-packages", "", "Comma-separated manufacturer option/package codes.")
	cmd.Flags().StringVar(&flagFeatures, "features", "", "Comma-separated feature tokens.")
	cmd.Flags().StringVar(&flagKeywords, "keywords", "", "Comma-separated provenance/history keyword tokens to apply before counting facet buckets. Supported values:...")
	cmd.Flags().StringVar(&flagVinPattern, "vin-pattern", "", "Comma-separated VIN masks, up to 10 distinct patterns. VIN characters match themselves, ? matches one VIN position,...")
	cmd.Flags().StringVar(&flagExcludeMake, "exclude-make", "", "Comma-separated makes to exclude.")
	cmd.Flags().StringVar(&flagExcludeModel, "exclude-model", "", "Comma-separated models to exclude.")
	cmd.Flags().StringVar(&flagExcludeTrim, "exclude-trim", "", "Comma-separated trims to exclude.")
	cmd.Flags().StringVar(&flagExcludeYear, "exclude-year", "", "Comma-separated model years to exclude.")
	cmd.Flags().StringVar(&flagExcludeState, "exclude-state", "", "Comma-separated dealer states to exclude.")
	cmd.Flags().StringVar(&flagExcludeInventoryType, "exclude-inventory-type", "", "Comma-separated inventory classes to exclude: new, used, certified. cpo is accepted as an alias for certified.")
	cmd.Flags().StringVar(&flagExcludeBodyType, "exclude-body-type", "", "Comma-separated body types to exclude.")
	cmd.Flags().StringVar(&flagExcludeTransmission, "exclude-transmission", "", "Comma-separated transmission values to exclude.")
	cmd.Flags().StringVar(&flagExcludeDrivetrain, "exclude-drivetrain", "", "Comma-separated drivetrain values to exclude.")
	cmd.Flags().StringVar(&flagExcludeVersion, "exclude-version", "", "Comma-separated vehicle versions to exclude.")
	cmd.Flags().StringVar(&flagExcludeEngine, "exclude-engine", "", "Comma-separated engine descriptions to exclude.")
	cmd.Flags().StringVar(&flagExcludeAssemblyLocation, "exclude-assembly-location", "", "Plus-separated assembly locations to exclude. Uses + to match the private API separator.")
	cmd.Flags().StringVar(&flagExcludeAssemblyCountry, "exclude-assembly-country", "", "Comma-separated assembly countries to exclude.")
	cmd.Flags().StringVar(&flagExcludeExteriorColor, "exclude-exterior-color", "", "Comma-separated exterior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeInteriorColor, "exclude-interior-color", "", "Comma-separated interior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeBaseExteriorColor, "exclude-base-exterior-color", "", "Comma-separated normalized exterior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeBaseInteriorColor, "exclude-base-interior-color", "", "Comma-separated normalized interior colors to exclude.")
	cmd.Flags().StringVar(&flagExcludeOptionsPackages, "exclude-options-packages", "", "Comma-separated manufacturer option/package codes to exclude.")
	cmd.Flags().StringVar(&flagExcludeFeatures, "exclude-features", "", "Comma-separated feature tokens to exclude.")
	cmd.Flags().StringVar(&flagExcludeFuelType, "exclude-fuel-type", "", "Comma-separated fuel types to exclude.")
	cmd.Flags().StringVar(&flagExcludePowertrainType, "exclude-powertrain-type", "", "Comma-separated powertrain types to exclude.")
	cmd.Flags().StringVar(&flagExcludeKeywords, "exclude-keywords", "", "Comma-separated keyword tokens to exclude.")
	cmd.Flags().StringVar(&flagInventoryStatus, "inventory-status", "", "Inventory mode used for facet counts. active is the default. (one of: active, sold)")
	cmd.Flags().StringVar(&flagSoldWithinDays, "sold-within-days", "", "Positive integer day window for sold inventory facets.")
	cmd.Flags().StringVar(&flagSnapshotDate, "snapshot-date", "", "Historical active-inventory snapshot date in YYYY-MM-DD format.")
	cmd.Flags().StringVar(&flagMinPrice, "min-price", "", "Minimum listed price in whole dollars.")
	cmd.Flags().StringVar(&flagMaxPrice, "max-price", "", "Maximum listed price in whole dollars.")
	cmd.Flags().StringVar(&flagMinMileage, "min-mileage", "", "Minimum odometer mileage.")
	cmd.Flags().StringVar(&flagMaxMileage, "max-mileage", "", "Maximum odometer mileage.")
	cmd.Flags().StringVar(&flagMinMsrp, "min-msrp", "", "Minimum combined MSRP in whole dollars.")
	cmd.Flags().StringVar(&flagMaxMsrp, "max-msrp", "", "Maximum combined MSRP in whole dollars.")
	cmd.Flags().StringVar(&flagMinDaysOnMarket, "min-days-on-market", "", "Minimum days on market.")
	cmd.Flags().StringVar(&flagMaxDaysOnMarket, "max-days-on-market", "", "Maximum days on market.")
	cmd.Flags().StringVar(&flagLatitude, "latitude", "", "Search origin latitude for radius filtering.")
	cmd.Flags().StringVar(&flagLongitude, "longitude", "", "Search origin longitude for radius filtering.")
	cmd.Flags().StringVar(&flagPostalCode, "postal-code", "", "US ZIP/postal search origin for radius filtering.")
	cmd.Flags().StringVar(&flagRadius, "radius", "", "Maximum distance from the search origin, in miles. Requires postal_code or latitude and longitude. Maximum 500.")
	cmd.Flags().StringVar(&flagBbox, "bbox", "", "Map viewport as west,south,east,north. Cannot be combined with radius. Maximum diagonal is 1000 miles.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
