// Copyright 2026 visor. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newVinsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagInclude string

	cmd := &cobra.Command{
		Use:         "vins <vin>",
		Short:       "Returns the current or latest known record for a VIN. Unknown VINs return 404 not_found_error; known VINs can return...",
		Long:        "Shortcut for 'vins get'. Returns the current or latest known record for a VIN. Unknown VINs return 404 not_found_error; known VINs can return...",
		Example:     "  visor vins example-value",
		Annotations: map[string]string{"pp:endpoint": "vins.get", "pp:method": "GET", "pp:path": "/v1/vins/{vin}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/vins/{vin}"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "vin is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "vin"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("vin is required\nUsage: %s <%s>", cmd.CommandPath(), "vin"))
			}
			path = replacePathParam(path, "vin", args[0])
			params := map[string]string{}
			if flagInclude != "" {
				params["include"] = fmt.Sprintf("%v", flagInclude)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "vins", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For structured output, wrap with provenance first so --select paths
			// match the documented envelope shape, e.g. results.data.vin.
			if flags.asJSON || flags.markdown || !isTerminal(cmd.OutOrStdout()) {
				wrapped, wrapErr := wrapWithProvenance(data, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutputWithFlags(cmd.OutOrStdout(), wrapped, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagInclude, "include", "", "Comma-separated optional expansions. Supported values are price_history and options.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
