#!/usr/bin/env python3
from pathlib import Path

root = Path(__file__).resolve().parents[1]
module = "github.com/visorvin/cli"

text_suffixes = {".go", ".md", ".yml", ".yaml", ".json", ".mod"}
for p in root.rglob("*"):
    if ".git" in p.parts or "scripts" in p.parts or p.is_dir():
        continue
    if p.name not in {"LICENSE", "NOTICE", "Makefile"} and p.suffix not in text_suffixes:
        continue
    try:
        s = p.read_text()
    except UnicodeDecodeError:
        continue
    s = s.replace("github.com/visorvin/visor-cli-pp-cli", module)
    s = s.replace("github.com/visorvin/cli-pp-cli", module)
    s = s.replace("github.com/visorvin/visor-cli", module)
    s = s.replace("module visor-pp-cli", f"module {module}")
    s = s.replace("module visor", f"module {module}")
    s = s.replace("visor-pp-cli/internal", f"{module}/internal")
    s = s.replace("visor/internal", f"{module}/internal")
    s = s.replace("https://github.com/visorvin/visor-cli", "https://github.com/visorvin/cli")
    s = s.replace("visorvin/visor-cli", "visorvin/cli")
    s = s.replace("Copyright 2026 cole", "Copyright 2026 Visor")
    s = s.replace("Copyright 2026 Cole", "Copyright 2026 Visor")
    s = s.replace(
        "// Copyright 2026 Visor. Licensed under Apache-2.0. See LICENSE.\n"
        "// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.",
        "// Copyright 2026 Visor. Licensed under Apache-2.0. See LICENSE.\n"
        "// Portions generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press).",
    )
    p.write_text(s)

(root / "NOTICE").write_text("""Visor CLI
Copyright 2026 Visor

This project includes code generated by CLI Printing Press
(https://github.com/mvanhorn/cli-printing-press). CLI Printing Press is
licensed separately under the MIT License.
""")

replacements = {
    root / "internal/client/client.go": {
        '''func (c *Client) writeCache(path string, params map[string]string, data json.RawMessage) {
\tos.MkdirAll(c.cacheDir, 0o755)
\tcacheFile := filepath.Join(c.cacheDir, c.cacheKey(path, params)+".json")
\tos.WriteFile(cacheFile, []byte(data), 0o644)
}
''': '''func (c *Client) writeCache(path string, params map[string]string, data json.RawMessage) {
\tif err := os.MkdirAll(c.cacheDir, 0o700); err != nil {
\t\treturn
\t}
\t_ = os.Chmod(c.cacheDir, 0o700)
\tcacheFile := filepath.Join(c.cacheDir, c.cacheKey(path, params)+".json")
\t_ = os.WriteFile(cacheFile, []byte(data), 0o600)
}
'''
    },
    root / "internal/cache/cache.go": {
        '''func (s *Store) Set(key string, value json.RawMessage) {
\t_ = os.MkdirAll(s.Dir, 0o755)
\t_ = os.WriteFile(s.path(key), []byte(value), 0o644)
}
''': '''func (s *Store) Set(key string, value json.RawMessage) {
\tif err := os.MkdirAll(s.Dir, 0o700); err != nil {
\t\treturn
\t}
\t_ = os.Chmod(s.Dir, 0o700)
\t_ = os.WriteFile(s.path(key), []byte(value), 0o600)
}
'''
    },
    root / "internal/store/store.go": {
        '''func OpenWithContext(ctx context.Context, dbPath string) (*Store, error) {
\tif err := os.MkdirAll(filepath.Dir(dbPath), 0o755); err != nil {
\t\treturn nil, fmt.Errorf("creating db directory: %w", err)
\t}
''': '''func OpenWithContext(ctx context.Context, dbPath string) (*Store, error) {
\tdbDir := filepath.Dir(dbPath)
\tif err := os.MkdirAll(dbDir, 0o700); err != nil {
\t\treturn nil, fmt.Errorf("creating db directory: %w", err)
\t}
\t_ = os.Chmod(dbDir, 0o700)
''',
        '''\tif err := s.migrate(ctx); err != nil {
\t\tdb.Close()
\t\treturn nil, fmt.Errorf("running migrations: %w", err)
\t}

\treturn s, nil
}
''': '''\tif err := s.migrate(ctx); err != nil {
\t\tdb.Close()
\t\treturn nil, fmt.Errorf("running migrations: %w", err)
\t}
\tsecureStoreFiles(dbPath)

\treturn s, nil
}

func secureStoreFiles(dbPath string) {
\tfor _, path := range []string{dbPath, dbPath + "-wal", dbPath + "-shm"} {
\t\tif _, err := os.Stat(path); err == nil {
\t\t\t_ = os.Chmod(path, 0o600)
\t\t}
\t}
}
'''
    },
}

for path, reps in replacements.items():
    if not path.exists():
        continue
    s = path.read_text()
    for old, new in reps.items():
        s = s.replace(old, new)
    path.write_text(s)
