// Copyright 2026 Visor. Licensed under Apache-2.0. See LICENSE.
// Portions generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press).

package main

import (
	"fmt"
	"os"

	"github.com/visorvin/cli/internal/cli"
)

func main() {
	if err := cli.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(cli.ExitCode(err))
	}
}
